// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fileMocks

import (
	"context"

	"github.com/starfrag-lab/retrowin-go/internal/file"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceMock creates a new instance of ServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceMock {
	mock := &ServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceMock is an autogenerated mock type for the Service type
type ServiceMock struct {
	mock.Mock
}

type ServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceMock) EXPECT() *ServiceMock_Expecter {
	return &ServiceMock_Expecter{mock: &_m.Mock}
}

// Copy provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Copy(ctx context.Context, fileKey string, cmd *file.CopyCommand) (*file.File, error) {
	ret := _mock.Called(ctx, fileKey, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Copy")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.CopyCommand) (*file.File, error)); ok {
		return returnFunc(ctx, fileKey, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.CopyCommand) *file.File); ok {
		r0 = returnFunc(ctx, fileKey, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *file.CopyCommand) error); ok {
		r1 = returnFunc(ctx, fileKey, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Copy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Copy'
type ServiceMock_Copy_Call struct {
	*mock.Call
}

// Copy is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
//   - cmd *file.CopyCommand
func (_e *ServiceMock_Expecter) Copy(ctx interface{}, fileKey interface{}, cmd interface{}) *ServiceMock_Copy_Call {
	return &ServiceMock_Copy_Call{Call: _e.mock.On("Copy", ctx, fileKey, cmd)}
}

func (_c *ServiceMock_Copy_Call) Run(run func(ctx context.Context, fileKey string, cmd *file.CopyCommand)) *ServiceMock_Copy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *file.CopyCommand
		if args[2] != nil {
			arg2 = args[2].(*file.CopyCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_Copy_Call) Return(file1 *file.File, err error) *ServiceMock_Copy_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_Copy_Call) RunAndReturn(run func(ctx context.Context, fileKey string, cmd *file.CopyCommand) (*file.File, error)) *ServiceMock_Copy_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Create(ctx context.Context, cmd *file.CreateCommand) (*file.File, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file.CreateCommand) (*file.File, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file.CreateCommand) *file.File); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file.CreateCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *file.CreateCommand
func (_e *ServiceMock_Expecter) Create(ctx interface{}, cmd interface{}) *ServiceMock_Create_Call {
	return &ServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *ServiceMock_Create_Call) Run(run func(ctx context.Context, cmd *file.CreateCommand)) *ServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file.CreateCommand
		if args[1] != nil {
			arg1 = args[1].(*file.CreateCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Create_Call) Return(file1 *file.File, err error) *ServiceMock_Create_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *file.CreateCommand) (*file.File, error)) *ServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Delete(ctx context.Context, fileKey string, permanent bool) error {
	ret := _mock.Called(ctx, fileKey, permanent)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, fileKey, permanent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
//   - permanent bool
func (_e *ServiceMock_Expecter) Delete(ctx interface{}, fileKey interface{}, permanent interface{}) *ServiceMock_Delete_Call {
	return &ServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, fileKey, permanent)}
}

func (_c *ServiceMock_Delete_Call) Run(run func(ctx context.Context, fileKey string, permanent bool)) *ServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_Delete_Call) Return(err error) *ServiceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, fileKey string, permanent bool) error) *ServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Get(ctx context.Context, fileKey string) (*file.File, error) {
	ret := _mock.Called(ctx, fileKey)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*file.File, error)); ok {
		return returnFunc(ctx, fileKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *file.File); ok {
		r0 = returnFunc(ctx, fileKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
func (_e *ServiceMock_Expecter) Get(ctx interface{}, fileKey interface{}) *ServiceMock_Get_Call {
	return &ServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, fileKey)}
}

func (_c *ServiceMock_Get_Call) Run(run func(ctx context.Context, fileKey string)) *ServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_Get_Call) Return(file1 *file.File, err error) *ServiceMock_Get_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_Get_Call) RunAndReturn(run func(ctx context.Context, fileKey string) (*file.File, error)) *ServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetByID(ctx context.Context, id int64) (*file.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*file.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *file.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ServiceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *ServiceMock_Expecter) GetByID(ctx interface{}, id interface{}) *ServiceMock_GetByID_Call {
	return &ServiceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ServiceMock_GetByID_Call) Run(run func(ctx context.Context, id int64)) *ServiceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetByID_Call) Return(file1 *file.File, err error) *ServiceMock_GetByID_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id int64) (*file.File, error)) *ServiceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChildren provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetChildren(ctx context.Context, fileKey string) ([]*file.File, error) {
	ret := _mock.Called(ctx, fileKey)

	if len(ret) == 0 {
		panic("no return value specified for GetChildren")
	}

	var r0 []*file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*file.File, error)); ok {
		return returnFunc(ctx, fileKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*file.File); ok {
		r0 = returnFunc(ctx, fileKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fileKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChildren'
type ServiceMock_GetChildren_Call struct {
	*mock.Call
}

// GetChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
func (_e *ServiceMock_Expecter) GetChildren(ctx interface{}, fileKey interface{}) *ServiceMock_GetChildren_Call {
	return &ServiceMock_GetChildren_Call{Call: _e.mock.On("GetChildren", ctx, fileKey)}
}

func (_c *ServiceMock_GetChildren_Call) Run(run func(ctx context.Context, fileKey string)) *ServiceMock_GetChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetChildren_Call) Return(files []*file.File, err error) *ServiceMock_GetChildren_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *ServiceMock_GetChildren_Call) RunAndReturn(run func(ctx context.Context, fileKey string) ([]*file.File, error)) *ServiceMock_GetChildren_Call {
	_c.Call.Return(run)
	return _c
}

// GetHome provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetHome(ctx context.Context, ownerID int64) (*file.File, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetHome")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*file.File, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *file.File); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetHome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHome'
type ServiceMock_GetHome_Call struct {
	*mock.Call
}

// GetHome is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *ServiceMock_Expecter) GetHome(ctx interface{}, ownerID interface{}) *ServiceMock_GetHome_Call {
	return &ServiceMock_GetHome_Call{Call: _e.mock.On("GetHome", ctx, ownerID)}
}

func (_c *ServiceMock_GetHome_Call) Run(run func(ctx context.Context, ownerID int64)) *ServiceMock_GetHome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetHome_Call) Return(file1 *file.File, err error) *ServiceMock_GetHome_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_GetHome_Call) RunAndReturn(run func(ctx context.Context, ownerID int64) (*file.File, error)) *ServiceMock_GetHome_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoot provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetRoot(ctx context.Context, ownerID int64) (*file.File, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetRoot")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*file.File, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *file.File); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoot'
type ServiceMock_GetRoot_Call struct {
	*mock.Call
}

// GetRoot is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *ServiceMock_Expecter) GetRoot(ctx interface{}, ownerID interface{}) *ServiceMock_GetRoot_Call {
	return &ServiceMock_GetRoot_Call{Call: _e.mock.On("GetRoot", ctx, ownerID)}
}

func (_c *ServiceMock_GetRoot_Call) Run(run func(ctx context.Context, ownerID int64)) *ServiceMock_GetRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetRoot_Call) Return(file1 *file.File, err error) *ServiceMock_GetRoot_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_GetRoot_Call) RunAndReturn(run func(ctx context.Context, ownerID int64) (*file.File, error)) *ServiceMock_GetRoot_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrash provides a mock function for the type ServiceMock
func (_mock *ServiceMock) GetTrash(ctx context.Context, ownerID int64) (*file.File, error) {
	ret := _mock.Called(ctx, ownerID)

	if len(ret) == 0 {
		panic("no return value specified for GetTrash")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*file.File, error)); ok {
		return returnFunc(ctx, ownerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *file.File); ok {
		r0 = returnFunc(ctx, ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, ownerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_GetTrash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrash'
type ServiceMock_GetTrash_Call struct {
	*mock.Call
}

// GetTrash is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerID int64
func (_e *ServiceMock_Expecter) GetTrash(ctx interface{}, ownerID interface{}) *ServiceMock_GetTrash_Call {
	return &ServiceMock_GetTrash_Call{Call: _e.mock.On("GetTrash", ctx, ownerID)}
}

func (_c *ServiceMock_GetTrash_Call) Run(run func(ctx context.Context, ownerID int64)) *ServiceMock_GetTrash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceMock_GetTrash_Call) Return(file1 *file.File, err error) *ServiceMock_GetTrash_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_GetTrash_Call) RunAndReturn(run func(ctx context.Context, ownerID int64) (*file.File, error)) *ServiceMock_GetTrash_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Move(ctx context.Context, fileKey string, cmd *file.MoveCommand) (*file.File, error) {
	ret := _mock.Called(ctx, fileKey, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.MoveCommand) (*file.File, error)); ok {
		return returnFunc(ctx, fileKey, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.MoveCommand) *file.File); ok {
		r0 = returnFunc(ctx, fileKey, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *file.MoveCommand) error); ok {
		r1 = returnFunc(ctx, fileKey, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type ServiceMock_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
//   - cmd *file.MoveCommand
func (_e *ServiceMock_Expecter) Move(ctx interface{}, fileKey interface{}, cmd interface{}) *ServiceMock_Move_Call {
	return &ServiceMock_Move_Call{Call: _e.mock.On("Move", ctx, fileKey, cmd)}
}

func (_c *ServiceMock_Move_Call) Run(run func(ctx context.Context, fileKey string, cmd *file.MoveCommand)) *ServiceMock_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *file.MoveCommand
		if args[2] != nil {
			arg2 = args[2].(*file.MoveCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_Move_Call) Return(file1 *file.File, err error) *ServiceMock_Move_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_Move_Call) RunAndReturn(run func(ctx context.Context, fileKey string, cmd *file.MoveCommand) (*file.File, error)) *ServiceMock_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ServiceMock
func (_mock *ServiceMock) Update(ctx context.Context, fileKey string, cmd *file.UpdateCommand) (*file.File, error) {
	ret := _mock.Called(ctx, fileKey, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *file.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.UpdateCommand) (*file.File, error)); ok {
		return returnFunc(ctx, fileKey, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *file.UpdateCommand) *file.File); ok {
		r0 = returnFunc(ctx, fileKey, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *file.UpdateCommand) error); ok {
		r1 = returnFunc(ctx, fileKey, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ServiceMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - fileKey string
//   - cmd *file.UpdateCommand
func (_e *ServiceMock_Expecter) Update(ctx interface{}, fileKey interface{}, cmd interface{}) *ServiceMock_Update_Call {
	return &ServiceMock_Update_Call{Call: _e.mock.On("Update", ctx, fileKey, cmd)}
}

func (_c *ServiceMock_Update_Call) Run(run func(ctx context.Context, fileKey string, cmd *file.UpdateCommand)) *ServiceMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *file.UpdateCommand
		if args[2] != nil {
			arg2 = args[2].(*file.UpdateCommand)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceMock_Update_Call) Return(file1 *file.File, err error) *ServiceMock_Update_Call {
	_c.Call.Return(file1, err)
	return _c
}

func (_c *ServiceMock_Update_Call) RunAndReturn(run func(ctx context.Context, fileKey string, cmd *file.UpdateCommand) (*file.File, error)) *ServiceMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
