// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fileMocks

import (
	"context"

	"github.com/starfrag-lab/retrowin-go/internal/file"
	mock "github.com/stretchr/testify/mock"
)

// NewFileInfoRepositoryMock creates a new instance of FileInfoRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileInfoRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileInfoRepositoryMock {
	mock := &FileInfoRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FileInfoRepositoryMock is an autogenerated mock type for the FileInfoRepository type
type FileInfoRepositoryMock struct {
	mock.Mock
}

type FileInfoRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *FileInfoRepositoryMock) EXPECT() *FileInfoRepositoryMock_Expecter {
	return &FileInfoRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type FileInfoRepositoryMock
func (_mock *FileInfoRepositoryMock) Create(ctx context.Context, fileID int64, byteSize int64) (*file.FileInfo, error) {
	ret := _mock.Called(ctx, fileID, byteSize)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *file.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*file.FileInfo, error)); ok {
		return returnFunc(ctx, fileID, byteSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *file.FileInfo); ok {
		r0 = returnFunc(ctx, fileID, byteSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, fileID, byteSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileInfoRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type FileInfoRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
//   - byteSize int64
func (_e *FileInfoRepositoryMock_Expecter) Create(ctx interface{}, fileID interface{}, byteSize interface{}) *FileInfoRepositoryMock_Create_Call {
	return &FileInfoRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, fileID, byteSize)}
}

func (_c *FileInfoRepositoryMock_Create_Call) Run(run func(ctx context.Context, fileID int64, byteSize int64)) *FileInfoRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FileInfoRepositoryMock_Create_Call) Return(fileInfo *file.FileInfo, err error) *FileInfoRepositoryMock_Create_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *FileInfoRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, fileID int64, byteSize int64) (*file.FileInfo, error)) *FileInfoRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type FileInfoRepositoryMock
func (_mock *FileInfoRepositoryMock) Delete(ctx context.Context, fileID int64) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// FileInfoRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type FileInfoRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
func (_e *FileInfoRepositoryMock_Expecter) Delete(ctx interface{}, fileID interface{}) *FileInfoRepositoryMock_Delete_Call {
	return &FileInfoRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, fileID)}
}

func (_c *FileInfoRepositoryMock_Delete_Call) Run(run func(ctx context.Context, fileID int64)) *FileInfoRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileInfoRepositoryMock_Delete_Call) Return(err error) *FileInfoRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *FileInfoRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, fileID int64) error) *FileInfoRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByFileID provides a mock function for the type FileInfoRepositoryMock
func (_mock *FileInfoRepositoryMock) GetByFileID(ctx context.Context, fileID int64) (*file.FileInfo, error) {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetByFileID")
	}

	var r0 *file.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*file.FileInfo, error)); ok {
		return returnFunc(ctx, fileID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *file.FileInfo); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileInfoRepositoryMock_GetByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByFileID'
type FileInfoRepositoryMock_GetByFileID_Call struct {
	*mock.Call
}

// GetByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
func (_e *FileInfoRepositoryMock_Expecter) GetByFileID(ctx interface{}, fileID interface{}) *FileInfoRepositoryMock_GetByFileID_Call {
	return &FileInfoRepositoryMock_GetByFileID_Call{Call: _e.mock.On("GetByFileID", ctx, fileID)}
}

func (_c *FileInfoRepositoryMock_GetByFileID_Call) Run(run func(ctx context.Context, fileID int64)) *FileInfoRepositoryMock_GetByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *FileInfoRepositoryMock_GetByFileID_Call) Return(fileInfo *file.FileInfo, err error) *FileInfoRepositoryMock_GetByFileID_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *FileInfoRepositoryMock_GetByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID int64) (*file.FileInfo, error)) *FileInfoRepositoryMock_GetByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type FileInfoRepositoryMock
func (_mock *FileInfoRepositoryMock) Update(ctx context.Context, fileID int64, byteSize int64) (*file.FileInfo, error) {
	ret := _mock.Called(ctx, fileID, byteSize)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *file.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) (*file.FileInfo, error)); ok {
		return returnFunc(ctx, fileID, byteSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) *file.FileInfo); ok {
		r0 = returnFunc(ctx, fileID, byteSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, fileID, byteSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FileInfoRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type FileInfoRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID int64
//   - byteSize int64
func (_e *FileInfoRepositoryMock_Expecter) Update(ctx interface{}, fileID interface{}, byteSize interface{}) *FileInfoRepositoryMock_Update_Call {
	return &FileInfoRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, fileID, byteSize)}
}

func (_c *FileInfoRepositoryMock_Update_Call) Run(run func(ctx context.Context, fileID int64, byteSize int64)) *FileInfoRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FileInfoRepositoryMock_Update_Call) Return(fileInfo *file.FileInfo, err error) *FileInfoRepositoryMock_Update_Call {
	_c.Call.Return(fileInfo, err)
	return _c
}

func (_c *FileInfoRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, fileID int64, byteSize int64) (*file.FileInfo, error)) *FileInfoRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
