all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{lower .InterfaceName}}.go"
structname: "{{.InterfaceName}}Mock"
pkgname: "{{.SrcPackageName}}Mocks"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/starfrag-lab/retrowin-go/internal:
    config:
      all: true
      recursive: true
