// Code generated by ent, DO NOT EDIT.

package usergroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldLTE(FieldID, id))
}

// UserSystemID applies equality check predicate on the "user_system_id" field. It's identical to UserSystemIDEQ.
func UserSystemID(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldUserSystemID, v))
}

// SystemGroupID applies equality check predicate on the "system_group_id" field. It's identical to SystemGroupIDEQ.
func SystemGroupID(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldSystemGroupID, v))
}

// UserSystemIDEQ applies the EQ predicate on the "user_system_id" field.
func UserSystemIDEQ(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldUserSystemID, v))
}

// UserSystemIDNEQ applies the NEQ predicate on the "user_system_id" field.
func UserSystemIDNEQ(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNEQ(FieldUserSystemID, v))
}

// UserSystemIDIn applies the In predicate on the "user_system_id" field.
func UserSystemIDIn(vs ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldIn(FieldUserSystemID, vs...))
}

// UserSystemIDNotIn applies the NotIn predicate on the "user_system_id" field.
func UserSystemIDNotIn(vs ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNotIn(FieldUserSystemID, vs...))
}

// SystemGroupIDEQ applies the EQ predicate on the "system_group_id" field.
func SystemGroupIDEQ(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldEQ(FieldSystemGroupID, v))
}

// SystemGroupIDNEQ applies the NEQ predicate on the "system_group_id" field.
func SystemGroupIDNEQ(v int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNEQ(FieldSystemGroupID, v))
}

// SystemGroupIDIn applies the In predicate on the "system_group_id" field.
func SystemGroupIDIn(vs ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldIn(FieldSystemGroupID, vs...))
}

// SystemGroupIDNotIn applies the NotIn predicate on the "system_group_id" field.
func SystemGroupIDNotIn(vs ...int) predicate.UserGroup {
	return predicate.UserGroup(sql.FieldNotIn(FieldSystemGroupID, vs...))
}

// HasUserSystem applies the HasEdge predicate on the "user_system" edge.
func HasUserSystem() predicate.UserGroup {
	return predicate.UserGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserSystemTable, UserSystemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserSystemWith applies the HasEdge predicate on the "user_system" edge with a given conditions (other predicates).
func HasUserSystemWith(preds ...predicate.UserSystem) predicate.UserGroup {
	return predicate.UserGroup(func(s *sql.Selector) {
		step := newUserSystemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSystemGroup applies the HasEdge predicate on the "system_group" edge.
func HasSystemGroup() predicate.UserGroup {
	return predicate.UserGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SystemGroupTable, SystemGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSystemGroupWith applies the HasEdge predicate on the "system_group" edge with a given conditions (other predicates).
func HasSystemGroupWith(preds ...predicate.SystemGroup) predicate.UserGroup {
	return predicate.UserGroup(func(s *sql.Selector) {
		step := newSystemGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserGroup) predicate.UserGroup {
	return predicate.UserGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserGroup) predicate.UserGroup {
	return predicate.UserGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserGroup) predicate.UserGroup {
	return predicate.UserGroup(sql.NotPredicates(p))
}
