// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddGroupMember implements addGroupMember operation.
	//
	// Add a user to a group.
	//
	// POST /systems/{systemId}/groups/{gid}/members/{uid}
	AddGroupMember(ctx context.Context, params AddGroupMemberParams) (AddGroupMemberRes, error)
	// Chmod implements chmod operation.
	//
	// Change permissions of a file or directory.
	//
	// PATCH /fs/{systemId}/chmod
	Chmod(ctx context.Context, req *ChmodRequest, params ChmodParams) (ChmodRes, error)
	// CompleteUpload implements completeUpload operation.
	//
	// Mark upload as complete and create inode.
	//
	// POST /fs/{systemId}/upload/complete
	CompleteUpload(ctx context.Context, req *CompleteUploadRequest, params CompleteUploadParams) (CompleteUploadRes, error)
	// CreateSystem implements createSystem operation.
	//
	// Create a new system with root user and directories.
	//
	// POST /systems
	CreateSystem(ctx context.Context, req *CreateSystemRequest) (CreateSystemRes, error)
	// CreateSystemGroup implements createSystemGroup operation.
	//
	// Create a new group in a system.
	//
	// POST /systems/{systemId}/groups
	CreateSystemGroup(ctx context.Context, req *CreateSystemGroupRequest, params CreateSystemGroupParams) (CreateSystemGroupRes, error)
	// CreateSystemUser implements createSystemUser operation.
	//
	// Add a user to a system.
	// UID assignment:
	// - If uid is -1 or not provided: Auto-assigned starting from 1000
	// - If uid is 0: Creates root user (superuser) - typically only for system initialization
	// - If uid is 1-999: Reserved for system users (e.g., daemon accounts)
	// - If uid is 1000+: Regular user with explicit UID
	// A private group with the same GID as UID is automatically created.
	//
	// POST /systems/{systemId}/users
	CreateSystemUser(ctx context.Context, req *CreateSystemUserRequest, params CreateSystemUserParams) (CreateSystemUserRes, error)
	// DeleteSystem implements deleteSystem operation.
	//
	// Delete a system and all associated data (inodes, objects, users, groups).
	//
	// DELETE /systems/{systemId}
	DeleteSystem(ctx context.Context, params DeleteSystemParams) (DeleteSystemRes, error)
	// DeleteSystemGroup implements deleteSystemGroup operation.
	//
	// Delete a group from a system.
	//
	// DELETE /systems/{systemId}/groups/{gid}
	DeleteSystemGroup(ctx context.Context, params DeleteSystemGroupParams) (DeleteSystemGroupRes, error)
	// DeleteSystemUser implements deleteSystemUser operation.
	//
	// Remove a user from a system.
	//
	// DELETE /systems/{systemId}/users/{uid}
	DeleteSystemUser(ctx context.Context, params DeleteSystemUserParams) (DeleteSystemUserRes, error)
	// DeleteUser implements deleteUser operation.
	//
	// Delete the current user.
	//
	// DELETE /user
	DeleteUser(ctx context.Context) (DeleteUserRes, error)
	// GetDownloadUrl implements getDownloadUrl operation.
	//
	// Get presigned download URL for a file.
	//
	// GET /fs/{systemId}/download
	GetDownloadUrl(ctx context.Context, params GetDownloadUrlParams) (GetDownloadUrlRes, error)
	// GetHealth implements getHealth operation.
	//
	// Check if the service is healthy.
	//
	// GET /health
	GetHealth(ctx context.Context) (GetHealthRes, error)
	// GetRootDirectory implements getRootDirectory operation.
	//
	// Get the root directory inode for a system.
	//
	// GET /fs/{systemId}/root
	GetRootDirectory(ctx context.Context, params GetRootDirectoryParams) (GetRootDirectoryRes, error)
	// GetSystem implements getSystem operation.
	//
	// Get detailed information about a system.
	//
	// GET /systems/{systemId}
	GetSystem(ctx context.Context, params GetSystemParams) (GetSystemRes, error)
	// GetSystemGroup implements getSystemGroup operation.
	//
	// Get detailed information about a system group.
	//
	// GET /systems/{systemId}/groups/{gid}
	GetSystemGroup(ctx context.Context, params GetSystemGroupParams) (GetSystemGroupRes, error)
	// GetSystemUser implements getSystemUser operation.
	//
	// Get detailed information about a system user.
	//
	// GET /systems/{systemId}/users/{uid}
	GetSystemUser(ctx context.Context, params GetSystemUserParams) (GetSystemUserRes, error)
	// GetUser implements getUser operation.
	//
	// Get the current user information.
	//
	// GET /user
	GetUser(ctx context.Context) (GetUserRes, error)
	// HandleCallback implements handleCallback operation.
	//
	// Handle OAuth callback from Keycloak.
	//
	// GET /auth/callback
	HandleCallback(ctx context.Context, params HandleCallbackParams) (HandleCallbackRes, error)
	// InitiateLogin implements initiateLogin operation.
	//
	// Start OIDC login flow and return authorization URL.
	//
	// GET /auth/login
	InitiateLogin(ctx context.Context) (InitiateLoginRes, error)
	// InitiateUpload implements initiateUpload operation.
	//
	// Start an upload session and get presigned URL.
	//
	// POST /fs/{systemId}/upload/initiate
	InitiateUpload(ctx context.Context, req *InitiateUploadRequest, params InitiateUploadParams) (InitiateUploadRes, error)
	// ListSystemGroups implements listSystemGroups operation.
	//
	// Get all groups in a system.
	//
	// GET /systems/{systemId}/groups
	ListSystemGroups(ctx context.Context, params ListSystemGroupsParams) (ListSystemGroupsRes, error)
	// ListSystemUsers implements listSystemUsers operation.
	//
	// Get all users in a system.
	//
	// GET /systems/{systemId}/users
	ListSystemUsers(ctx context.Context, params ListSystemUsersParams) (ListSystemUsersRes, error)
	// ListSystems implements listSystems operation.
	//
	// Get a list of all systems.
	//
	// GET /systems
	ListSystems(ctx context.Context) (ListSystemsRes, error)
	// Ln implements ln operation.
	//
	// Create a symbolic link (symlinkat).
	//
	// POST /syscall/{systemId}/ln
	Ln(ctx context.Context, req *SymlinkRequest, params LnParams) (LnRes, error)
	// Logout implements logout operation.
	//
	// Logout and delete session (idempotent - always returns 204).
	//
	// POST /auth/logout
	Logout(ctx context.Context) error
	// Ls implements ls operation.
	//
	// List contents of a directory (like Unix ls command, getdents64).
	//
	// GET /syscall/{systemId}/ls
	Ls(ctx context.Context, params LsParams) (LsRes, error)
	// Mkdir implements mkdir operation.
	//
	// Create a new directory at the specified path (mkdirat).
	//
	// POST /syscall/{systemId}/mkdir
	Mkdir(ctx context.Context, req *MkdirRequest, params MkdirParams) (MkdirRes, error)
	// Mv implements mv operation.
	//
	// Move files or directories (like Unix mv). Accepts multiple sources with a single destination.
	// If destination is a directory, all sources are moved into it.
	// If destination is a new path, source is renamed/moved.
	//
	// POST /syscall/{systemId}/mv
	Mv(ctx context.Context, req *MvRequest, params MvParams) (MvRes, error)
	// RemoveGroupMember implements removeGroupMember operation.
	//
	// Remove a user from a group.
	//
	// DELETE /systems/{systemId}/groups/{gid}/members/{uid}
	RemoveGroupMember(ctx context.Context, params RemoveGroupMemberParams) (RemoveGroupMemberRes, error)
	// Rename implements rename operation.
	//
	// Rename a file or directory within the same parent directory (renameat).
	//
	// POST /syscall/{systemId}/rename
	Rename(ctx context.Context, req *RenameRequest, params RenameParams) (RenameRes, error)
	// Rm implements rm operation.
	//
	// Remove files or directories (like Unix rm). Accepts multiple paths for bulk deletion.
	//
	// POST /syscall/{systemId}/rm
	Rm(ctx context.Context, req *RmRequest, params RmParams) (RmRes, error)
	// StatPath implements statPath operation.
	//
	// Get inode metadata for a given path.
	//
	// GET /fs/{systemId}/stat
	StatPath(ctx context.Context, params StatPathParams) (StatPathRes, error)
	// Unlink implements unlink operation.
	//
	// Delete a file or directory at the specified path (unlinkat).
	//
	// DELETE /syscall/{systemId}/unlink
	Unlink(ctx context.Context, params UnlinkParams) (UnlinkRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
