// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userMocks

import (
	"context"

	"github.com/starfrag-lab/retrowin-go/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserServiceMock is an autogenerated mock type for the UserService type
type UserServiceMock struct {
	mock.Mock
}

type UserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceMock) EXPECT() *UserServiceMock_Expecter {
	return &UserServiceMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) Create(ctx context.Context, cmd *user.CreateCommand) (*user.User, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateCommand) (*user.User, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.CreateCommand) *user.User); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.CreateCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *user.CreateCommand
func (_e *UserServiceMock_Expecter) Create(ctx interface{}, cmd interface{}) *UserServiceMock_Create_Call {
	return &UserServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *UserServiceMock_Create_Call) Run(run func(ctx context.Context, cmd *user.CreateCommand)) *UserServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.CreateCommand
		if args[1] != nil {
			arg1 = args[1].(*user.CreateCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServiceMock_Create_Call) Return(user1 *user.User, err error) *UserServiceMock_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserServiceMock_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *user.CreateCommand) (*user.User, error)) *UserServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) Delete(ctx context.Context, provider string, providerID string) error {
	ret := _mock.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, provider, providerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *UserServiceMock_Expecter) Delete(ctx interface{}, provider interface{}, providerID interface{}) *UserServiceMock_Delete_Call {
	return &UserServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, provider, providerID)}
}

func (_c *UserServiceMock_Delete_Call) Run(run func(ctx context.Context, provider string, providerID string)) *UserServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserServiceMock_Delete_Call) Return(err error) *UserServiceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserServiceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, provider string, providerID string) error) *UserServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrCreateByOIDC provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) FindOrCreateByOIDC(ctx context.Context, provider string, subject string, username string) (string, error) {
	ret := _mock.Called(ctx, provider, subject, username)

	if len(ret) == 0 {
		panic("no return value specified for FindOrCreateByOIDC")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, provider, subject, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, provider, subject, username)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, provider, subject, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_FindOrCreateByOIDC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrCreateByOIDC'
type UserServiceMock_FindOrCreateByOIDC_Call struct {
	*mock.Call
}

// FindOrCreateByOIDC is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - subject string
//   - username string
func (_e *UserServiceMock_Expecter) FindOrCreateByOIDC(ctx interface{}, provider interface{}, subject interface{}, username interface{}) *UserServiceMock_FindOrCreateByOIDC_Call {
	return &UserServiceMock_FindOrCreateByOIDC_Call{Call: _e.mock.On("FindOrCreateByOIDC", ctx, provider, subject, username)}
}

func (_c *UserServiceMock_FindOrCreateByOIDC_Call) Run(run func(ctx context.Context, provider string, subject string, username string)) *UserServiceMock_FindOrCreateByOIDC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserServiceMock_FindOrCreateByOIDC_Call) Return(s string, err error) *UserServiceMock_FindOrCreateByOIDC_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UserServiceMock_FindOrCreateByOIDC_Call) RunAndReturn(run func(ctx context.Context, provider string, subject string, username string) (string, error)) *UserServiceMock_FindOrCreateByOIDC_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) Get(ctx context.Context, provider string, providerID string) (*user.User, error) {
	ret := _mock.Called(ctx, provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*user.User, error)); ok {
		return returnFunc(ctx, provider, providerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *user.User); ok {
		r0 = returnFunc(ctx, provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, providerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserServiceMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - providerID string
func (_e *UserServiceMock_Expecter) Get(ctx interface{}, provider interface{}, providerID interface{}) *UserServiceMock_Get_Call {
	return &UserServiceMock_Get_Call{Call: _e.mock.On("Get", ctx, provider, providerID)}
}

func (_c *UserServiceMock_Get_Call) Run(run func(ctx context.Context, provider string, providerID string)) *UserServiceMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserServiceMock_Get_Call) Return(user1 *user.User, err error) *UserServiceMock_Get_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserServiceMock_Get_Call) RunAndReturn(run func(ctx context.Context, provider string, providerID string) (*user.User, error)) *UserServiceMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) GetByID(ctx context.Context, id string) (*user.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type UserServiceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserServiceMock_Expecter) GetByID(ctx interface{}, id interface{}) *UserServiceMock_GetByID_Call {
	return &UserServiceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *UserServiceMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *UserServiceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServiceMock_GetByID_Call) Return(user1 *user.User, err error) *UserServiceMock_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserServiceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*user.User, error)) *UserServiceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) GetByUsername(ctx context.Context, username string) (*user.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *user.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*user.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *user.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type UserServiceMock_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *UserServiceMock_Expecter) GetByUsername(ctx interface{}, username interface{}) *UserServiceMock_GetByUsername_Call {
	return &UserServiceMock_GetByUsername_Call{Call: _e.mock.On("GetByUsername", ctx, username)}
}

func (_c *UserServiceMock_GetByUsername_Call) Run(run func(ctx context.Context, username string)) *UserServiceMock_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServiceMock_GetByUsername_Call) Return(user1 *user.User, err error) *UserServiceMock_GetByUsername_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserServiceMock_GetByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*user.User, error)) *UserServiceMock_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}
