// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userMocks

import (
	"context"

	"github.com/starfrag-lab/retrowin-go/internal/user"
	mock "github.com/stretchr/testify/mock"
)

// NewServiceStatusRepositoryMock creates a new instance of ServiceStatusRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServiceStatusRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServiceStatusRepositoryMock {
	mock := &ServiceStatusRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ServiceStatusRepositoryMock is an autogenerated mock type for the ServiceStatusRepository type
type ServiceStatusRepositoryMock struct {
	mock.Mock
}

type ServiceStatusRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ServiceStatusRepositoryMock) EXPECT() *ServiceStatusRepositoryMock_Expecter {
	return &ServiceStatusRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ServiceStatusRepositoryMock
func (_mock *ServiceStatusRepositoryMock) Create(ctx context.Context, userID int64) (*user.ServiceStatus, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *user.ServiceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*user.ServiceStatus, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *user.ServiceStatus); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ServiceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceStatusRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ServiceStatusRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceStatusRepositoryMock_Expecter) Create(ctx interface{}, userID interface{}) *ServiceStatusRepositoryMock_Create_Call {
	return &ServiceStatusRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, userID)}
}

func (_c *ServiceStatusRepositoryMock_Create_Call) Run(run func(ctx context.Context, userID int64)) *ServiceStatusRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceStatusRepositoryMock_Create_Call) Return(serviceStatus *user.ServiceStatus, err error) *ServiceStatusRepositoryMock_Create_Call {
	_c.Call.Return(serviceStatus, err)
	return _c
}

func (_c *ServiceStatusRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*user.ServiceStatus, error)) *ServiceStatusRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ServiceStatusRepositoryMock
func (_mock *ServiceStatusRepositoryMock) Delete(ctx context.Context, userID int64) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ServiceStatusRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ServiceStatusRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceStatusRepositoryMock_Expecter) Delete(ctx interface{}, userID interface{}) *ServiceStatusRepositoryMock_Delete_Call {
	return &ServiceStatusRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, userID)}
}

func (_c *ServiceStatusRepositoryMock_Delete_Call) Run(run func(ctx context.Context, userID int64)) *ServiceStatusRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceStatusRepositoryMock_Delete_Call) Return(err error) *ServiceStatusRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ServiceStatusRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, userID int64) error) *ServiceStatusRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type ServiceStatusRepositoryMock
func (_mock *ServiceStatusRepositoryMock) GetByUserID(ctx context.Context, userID int64) (*user.ServiceStatus, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *user.ServiceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (*user.ServiceStatus, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) *user.ServiceStatus); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ServiceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceStatusRepositoryMock_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type ServiceStatusRepositoryMock_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *ServiceStatusRepositoryMock_Expecter) GetByUserID(ctx interface{}, userID interface{}) *ServiceStatusRepositoryMock_GetByUserID_Call {
	return &ServiceStatusRepositoryMock_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *ServiceStatusRepositoryMock_GetByUserID_Call) Run(run func(ctx context.Context, userID int64)) *ServiceStatusRepositoryMock_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ServiceStatusRepositoryMock_GetByUserID_Call) Return(serviceStatus *user.ServiceStatus, err error) *ServiceStatusRepositoryMock_GetByUserID_Call {
	_c.Call.Return(serviceStatus, err)
	return _c
}

func (_c *ServiceStatusRepositoryMock_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int64) (*user.ServiceStatus, error)) *ServiceStatusRepositoryMock_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ServiceStatusRepositoryMock
func (_mock *ServiceStatusRepositoryMock) Update(ctx context.Context, userID int64, available bool) (*user.ServiceStatus, error) {
	ret := _mock.Called(ctx, userID, available)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *user.ServiceStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) (*user.ServiceStatus, error)); ok {
		return returnFunc(ctx, userID, available)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, bool) *user.ServiceStatus); ok {
		r0 = returnFunc(ctx, userID, available)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.ServiceStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, bool) error); ok {
		r1 = returnFunc(ctx, userID, available)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ServiceStatusRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ServiceStatusRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - available bool
func (_e *ServiceStatusRepositoryMock_Expecter) Update(ctx interface{}, userID interface{}, available interface{}) *ServiceStatusRepositoryMock_Update_Call {
	return &ServiceStatusRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, userID, available)}
}

func (_c *ServiceStatusRepositoryMock_Update_Call) Run(run func(ctx context.Context, userID int64, available bool)) *ServiceStatusRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ServiceStatusRepositoryMock_Update_Call) Return(serviceStatus *user.ServiceStatus, err error) *ServiceStatusRepositoryMock_Update_Call {
	_c.Call.Return(serviceStatus, err)
	return _c
}

func (_c *ServiceStatusRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, userID int64, available bool) (*user.ServiceStatus, error)) *ServiceStatusRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
