// Code generated by ent, DO NOT EDIT.

package symlink

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Symlink {
	return predicate.Symlink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Symlink {
	return predicate.Symlink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Symlink {
	return predicate.Symlink(sql.FieldLTE(FieldID, id))
}

// InodeID applies equality check predicate on the "inode_id" field. It's identical to InodeIDEQ.
func InodeID(v int64) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldInodeID, v))
}

// TargetPath applies equality check predicate on the "target_path" field. It's identical to TargetPathEQ.
func TargetPath(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldTargetPath, v))
}

// InodeIDEQ applies the EQ predicate on the "inode_id" field.
func InodeIDEQ(v int64) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldInodeID, v))
}

// InodeIDNEQ applies the NEQ predicate on the "inode_id" field.
func InodeIDNEQ(v int64) predicate.Symlink {
	return predicate.Symlink(sql.FieldNEQ(FieldInodeID, v))
}

// InodeIDIn applies the In predicate on the "inode_id" field.
func InodeIDIn(vs ...int64) predicate.Symlink {
	return predicate.Symlink(sql.FieldIn(FieldInodeID, vs...))
}

// InodeIDNotIn applies the NotIn predicate on the "inode_id" field.
func InodeIDNotIn(vs ...int64) predicate.Symlink {
	return predicate.Symlink(sql.FieldNotIn(FieldInodeID, vs...))
}

// TargetPathEQ applies the EQ predicate on the "target_path" field.
func TargetPathEQ(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldEQ(FieldTargetPath, v))
}

// TargetPathNEQ applies the NEQ predicate on the "target_path" field.
func TargetPathNEQ(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldNEQ(FieldTargetPath, v))
}

// TargetPathIn applies the In predicate on the "target_path" field.
func TargetPathIn(vs ...string) predicate.Symlink {
	return predicate.Symlink(sql.FieldIn(FieldTargetPath, vs...))
}

// TargetPathNotIn applies the NotIn predicate on the "target_path" field.
func TargetPathNotIn(vs ...string) predicate.Symlink {
	return predicate.Symlink(sql.FieldNotIn(FieldTargetPath, vs...))
}

// TargetPathGT applies the GT predicate on the "target_path" field.
func TargetPathGT(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldGT(FieldTargetPath, v))
}

// TargetPathGTE applies the GTE predicate on the "target_path" field.
func TargetPathGTE(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldGTE(FieldTargetPath, v))
}

// TargetPathLT applies the LT predicate on the "target_path" field.
func TargetPathLT(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldLT(FieldTargetPath, v))
}

// TargetPathLTE applies the LTE predicate on the "target_path" field.
func TargetPathLTE(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldLTE(FieldTargetPath, v))
}

// TargetPathContains applies the Contains predicate on the "target_path" field.
func TargetPathContains(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldContains(FieldTargetPath, v))
}

// TargetPathHasPrefix applies the HasPrefix predicate on the "target_path" field.
func TargetPathHasPrefix(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldHasPrefix(FieldTargetPath, v))
}

// TargetPathHasSuffix applies the HasSuffix predicate on the "target_path" field.
func TargetPathHasSuffix(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldHasSuffix(FieldTargetPath, v))
}

// TargetPathEqualFold applies the EqualFold predicate on the "target_path" field.
func TargetPathEqualFold(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldEqualFold(FieldTargetPath, v))
}

// TargetPathContainsFold applies the ContainsFold predicate on the "target_path" field.
func TargetPathContainsFold(v string) predicate.Symlink {
	return predicate.Symlink(sql.FieldContainsFold(FieldTargetPath, v))
}

// HasInode applies the HasEdge predicate on the "inode" edge.
func HasInode() predicate.Symlink {
	return predicate.Symlink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, InodeTable, InodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInodeWith applies the HasEdge predicate on the "inode" edge with a given conditions (other predicates).
func HasInodeWith(preds ...predicate.Inode) predicate.Symlink {
	return predicate.Symlink(func(s *sql.Selector) {
		step := newInodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Symlink) predicate.Symlink {
	return predicate.Symlink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Symlink) predicate.Symlink {
	return predicate.Symlink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Symlink) predicate.Symlink {
	return predicate.Symlink(sql.NotPredicates(p))
}
