// Code generated by ent, DO NOT EDIT.

package systemgroup

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLTE(FieldID, id))
}

// SystemID applies equality check predicate on the "system_id" field. It's identical to SystemIDEQ.
func SystemID(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldSystemID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldName, v))
}

// Gid applies equality check predicate on the "gid" field. It's identical to GidEQ.
func Gid(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldGid, v))
}

// SystemIDEQ applies the EQ predicate on the "system_id" field.
func SystemIDEQ(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldSystemID, v))
}

// SystemIDNEQ applies the NEQ predicate on the "system_id" field.
func SystemIDNEQ(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNEQ(FieldSystemID, v))
}

// SystemIDIn applies the In predicate on the "system_id" field.
func SystemIDIn(vs ...string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldIn(FieldSystemID, vs...))
}

// SystemIDNotIn applies the NotIn predicate on the "system_id" field.
func SystemIDNotIn(vs ...string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNotIn(FieldSystemID, vs...))
}

// SystemIDGT applies the GT predicate on the "system_id" field.
func SystemIDGT(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGT(FieldSystemID, v))
}

// SystemIDGTE applies the GTE predicate on the "system_id" field.
func SystemIDGTE(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGTE(FieldSystemID, v))
}

// SystemIDLT applies the LT predicate on the "system_id" field.
func SystemIDLT(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLT(FieldSystemID, v))
}

// SystemIDLTE applies the LTE predicate on the "system_id" field.
func SystemIDLTE(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLTE(FieldSystemID, v))
}

// SystemIDContains applies the Contains predicate on the "system_id" field.
func SystemIDContains(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldContains(FieldSystemID, v))
}

// SystemIDHasPrefix applies the HasPrefix predicate on the "system_id" field.
func SystemIDHasPrefix(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldHasPrefix(FieldSystemID, v))
}

// SystemIDHasSuffix applies the HasSuffix predicate on the "system_id" field.
func SystemIDHasSuffix(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldHasSuffix(FieldSystemID, v))
}

// SystemIDEqualFold applies the EqualFold predicate on the "system_id" field.
func SystemIDEqualFold(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEqualFold(FieldSystemID, v))
}

// SystemIDContainsFold applies the ContainsFold predicate on the "system_id" field.
func SystemIDContainsFold(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldContainsFold(FieldSystemID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldContainsFold(FieldName, v))
}

// GidEQ applies the EQ predicate on the "gid" field.
func GidEQ(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldEQ(FieldGid, v))
}

// GidNEQ applies the NEQ predicate on the "gid" field.
func GidNEQ(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNEQ(FieldGid, v))
}

// GidIn applies the In predicate on the "gid" field.
func GidIn(vs ...int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldIn(FieldGid, vs...))
}

// GidNotIn applies the NotIn predicate on the "gid" field.
func GidNotIn(vs ...int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldNotIn(FieldGid, vs...))
}

// GidGT applies the GT predicate on the "gid" field.
func GidGT(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGT(FieldGid, v))
}

// GidGTE applies the GTE predicate on the "gid" field.
func GidGTE(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldGTE(FieldGid, v))
}

// GidLT applies the LT predicate on the "gid" field.
func GidLT(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLT(FieldGid, v))
}

// GidLTE applies the LTE predicate on the "gid" field.
func GidLTE(v int) predicate.SystemGroup {
	return predicate.SystemGroup(sql.FieldLTE(FieldGid, v))
}

// HasSystem applies the HasEdge predicate on the "system" edge.
func HasSystem() predicate.SystemGroup {
	return predicate.SystemGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, SystemTable, SystemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSystemWith applies the HasEdge predicate on the "system" edge with a given conditions (other predicates).
func HasSystemWith(preds ...predicate.System) predicate.SystemGroup {
	return predicate.SystemGroup(func(s *sql.Selector) {
		step := newSystemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsers applies the HasEdge predicate on the "users" edge.
func HasUsers() predicate.SystemGroup {
	return predicate.SystemGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UsersTable, UsersPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.UserSystem) predicate.SystemGroup {
	return predicate.SystemGroup(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SystemGroup) predicate.SystemGroup {
	return predicate.SystemGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SystemGroup) predicate.SystemGroup {
	return predicate.SystemGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SystemGroup) predicate.SystemGroup {
	return predicate.SystemGroup(sql.NotPredicates(p))
}
