// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sessionMocks

import (
	"context"

	"github.com/starfrag-lab/retrowin-go/internal/session"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Delete(ctx context.Context, id session.SessionID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.SessionID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id session.SessionID
func (_e *SessionRepositoryMock_Expecter) Delete(ctx interface{}, id interface{}) *SessionRepositoryMock_Delete_Call {
	return &SessionRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *SessionRepositoryMock_Delete_Call) Run(run func(ctx context.Context, id session.SessionID)) *SessionRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.SessionID
		if args[1] != nil {
			arg1 = args[1].(session.SessionID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Delete_Call) Return(err error) *SessionRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id session.SessionID) error) *SessionRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByUserID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) DeleteByUserID(ctx context.Context, userID string) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_DeleteByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByUserID'
type SessionRepositoryMock_DeleteByUserID_Call struct {
	*mock.Call
}

// DeleteByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *SessionRepositoryMock_Expecter) DeleteByUserID(ctx interface{}, userID interface{}) *SessionRepositoryMock_DeleteByUserID_Call {
	return &SessionRepositoryMock_DeleteByUserID_Call{Call: _e.mock.On("DeleteByUserID", ctx, userID)}
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) Run(run func(ctx context.Context, userID string)) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) Return(err error) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_DeleteByUserID_Call) RunAndReturn(run func(ctx context.Context, userID string) error) *SessionRepositoryMock_DeleteByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Get(ctx context.Context, id session.SessionID) (*session.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *session.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.SessionID) (*session.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, session.SessionID) *session.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*session.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, session.SessionID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type SessionRepositoryMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id session.SessionID
func (_e *SessionRepositoryMock_Expecter) Get(ctx interface{}, id interface{}) *SessionRepositoryMock_Get_Call {
	return &SessionRepositoryMock_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *SessionRepositoryMock_Get_Call) Run(run func(ctx context.Context, id session.SessionID)) *SessionRepositoryMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 session.SessionID
		if args[1] != nil {
			arg1 = args[1].(session.SessionID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Get_Call) Return(session1 *session.Session, err error) *SessionRepositoryMock_Get_Call {
	_c.Call.Return(session1, err)
	return _c
}

func (_c *SessionRepositoryMock_Get_Call) RunAndReturn(run func(ctx context.Context, id session.SessionID) (*session.Session, error)) *SessionRepositoryMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Save(ctx context.Context, session1 *session.Session) error {
	ret := _mock.Called(ctx, session1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *session.Session) error); ok {
		r0 = returnFunc(ctx, session1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type SessionRepositoryMock_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - session1 *session.Session
func (_e *SessionRepositoryMock_Expecter) Save(ctx interface{}, session1 interface{}) *SessionRepositoryMock_Save_Call {
	return &SessionRepositoryMock_Save_Call{Call: _e.mock.On("Save", ctx, session1)}
}

func (_c *SessionRepositoryMock_Save_Call) Run(run func(ctx context.Context, session1 *session.Session)) *SessionRepositoryMock_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *session.Session
		if args[1] != nil {
			arg1 = args[1].(*session.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Save_Call) Return(err error) *SessionRepositoryMock_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Save_Call) RunAndReturn(run func(ctx context.Context, session1 *session.Session) error) *SessionRepositoryMock_Save_Call {
	_c.Call.Return(run)
	return _c
}
