// Code generated by ogen, DO NOT EDIT.

package apiv1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CompleteUploadParams is parameters of completeUpload operation.
type CompleteUploadParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackCompleteUploadParams(packed middleware.Parameters) (params CompleteUploadParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCompleteUploadParams(args [1]string, argsEscaped bool, r *http.Request) (params CompleteUploadParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// CopyFileParams is parameters of copyFile operation.
type CopyFileParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackCopyFileParams(packed middleware.Parameters) (params CopyFileParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeCopyFileParams(args [1]string, argsEscaped bool, r *http.Request) (params CopyFileParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// DeleteFileParams is parameters of deleteFile operation.
type DeleteFileParams struct {
	// File key (UUID).
	FileKey uuid.UUID
	// Permanently delete (bypass trash).
	Permanent OptBool `json:",omitempty,omitzero"`
}

func unpackDeleteFileParams(packed middleware.Parameters) (params DeleteFileParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	{
		key := middleware.ParameterKey{
			Name: "permanent",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Permanent = v.(OptBool)
		}
	}
	return params
}

func decodeDeleteFileParams(args [1]string, argsEscaped bool, r *http.Request) (params DeleteFileParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	// Set default value for query: permanent.
	{
		val := bool(false)
		params.Permanent.SetTo(val)
	}
	// Decode query: permanent.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "permanent",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotPermanentVal bool
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToBool(val)
					if err != nil {
						return err
					}

					paramsDotPermanentVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Permanent.SetTo(paramsDotPermanentVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "permanent",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetFileChildrenParams is parameters of getFileChildren operation.
type GetFileChildrenParams struct {
	// Container file key (UUID).
	FileKey uuid.UUID
}

func unpackGetFileChildrenParams(packed middleware.Parameters) (params GetFileChildrenParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetFileChildrenParams(args [1]string, argsEscaped bool, r *http.Request) (params GetFileChildrenParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetFileInfoParams is parameters of getFileInfo operation.
type GetFileInfoParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackGetFileInfoParams(packed middleware.Parameters) (params GetFileInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetFileInfoParams(args [1]string, argsEscaped bool, r *http.Request) (params GetFileInfoParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetStreamTokenParams is parameters of getStreamToken operation.
type GetStreamTokenParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackGetStreamTokenParams(packed middleware.Parameters) (params GetStreamTokenParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetStreamTokenParams(args [1]string, argsEscaped bool, r *http.Request) (params GetStreamTokenParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// GetUploadTokenParams is parameters of getUploadToken operation.
type GetUploadTokenParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackGetUploadTokenParams(packed middleware.Parameters) (params GetUploadTokenParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetUploadTokenParams(args [1]string, argsEscaped bool, r *http.Request) (params GetUploadTokenParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// MoveFileParams is parameters of moveFile operation.
type MoveFileParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackMoveFileParams(packed middleware.Parameters) (params MoveFileParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeMoveFileParams(args [1]string, argsEscaped bool, r *http.Request) (params MoveFileParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// UpdateFileParams is parameters of updateFile operation.
type UpdateFileParams struct {
	// File key (UUID).
	FileKey uuid.UUID
}

func unpackUpdateFileParams(packed middleware.Parameters) (params UpdateFileParams) {
	{
		key := middleware.ParameterKey{
			Name: "fileKey",
			In:   "path",
		}
		params.FileKey = packed[key].(uuid.UUID)
	}
	return params
}

func decodeUpdateFileParams(args [1]string, argsEscaped bool, r *http.Request) (params UpdateFileParams, _ error) {
	// Decode path: fileKey.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "fileKey",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.FileKey = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fileKey",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
