// Code generated by ogen, DO NOT EDIT.

package apiv1

import (
	"net/url"
	"time"
)

// SetFake set fake values.
func (s *AddGroupMemberNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = AddGroupMemberNotFound(unwrapped)
}

// SetFake set fake values.
func (s *AddGroupMemberUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = AddGroupMemberUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CallbackRequest) SetFake() {
	{
		{
			s.Code = "string"
		}
	}
	{
		{
			s.State = "string"
		}
	}
}

// SetFake set fake values.
func (s *CallbackResponse) SetFake() {
	{
		{
			s.SessionId = "string"
		}
	}
	{
		{
			s.UserId = "string"
		}
	}
	{
		{
			s.ExpiresAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ChmodBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ChmodBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *ChmodForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ChmodForbidden(unwrapped)
}

// SetFake set fake values.
func (s *ChmodNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ChmodNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ChmodRequest) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Mode = int32(0)
		}
	}
}

// SetFake set fake values.
func (s *ChmodUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ChmodUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CompleteUploadBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CompleteUploadBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *CompleteUploadNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CompleteUploadNotFound(unwrapped)
}

// SetFake set fake values.
func (s *CompleteUploadRequest) SetFake() {
	{
		{
			s.ObjectId = "string"
		}
	}
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Mode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CompleteUploadUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CompleteUploadUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CreateSymlinkBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSymlinkBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *CreateSymlinkForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSymlinkForbidden(unwrapped)
}

// SetFake set fake values.
func (s *CreateSymlinkNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSymlinkNotFound(unwrapped)
}

// SetFake set fake values.
func (s *CreateSymlinkUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSymlinkUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemGroupBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemGroupBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemGroupConflict) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemGroupConflict(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemGroupNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemGroupNotFound(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemGroupRequest) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Gid.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSystemGroupUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemGroupUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemRequest) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSystemUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemUserBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemUserBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemUserConflict) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemUserConflict(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemUserNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemUserNotFound(unwrapped)
}

// SetFake set fake values.
func (s *CreateSystemUserRequest) SetFake() {
	{
		{
			s.UserId = "string"
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.UID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CreateSystemUserUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = CreateSystemUserUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *DeleteSystemGroupNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteSystemGroupNotFound(unwrapped)
}

// SetFake set fake values.
func (s *DeleteSystemGroupUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteSystemGroupUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *DeleteSystemUserNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteSystemUserNotFound(unwrapped)
}

// SetFake set fake values.
func (s *DeleteSystemUserUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteSystemUserUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *DeleteUserNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteUserNotFound(unwrapped)
}

// SetFake set fake values.
func (s *DeleteUserUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = DeleteUserUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *DirContentResponse) SetFake() {
	{
		{
			s.Entries = nil
			for i := 0; i < 0; i++ {
				var elem DirEntry
				{
					elem.SetFake()
				}
				s.Entries = append(s.Entries, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *DirEntry) SetFake() {
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.InodeId = "string"
		}
	}
	{
		{
			s.FileType = int32(0)
		}
	}
}

// SetFake set fake values.
func (s *DownloadURL) SetFake() {
	{
		{
			s.DownloadUrl = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
		}
	}
	{
		{
			s.ExpiresAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *DownloadURLResponse) SetFake() {
	{
		{
			s.DownloadUrl.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ErrorError) SetFake() {
	{
		{
			s.Type = "string"
		}
	}
	{
		{
			s.Message = "string"
		}
	}
}

// SetFake set fake values.
func (s *GetDownloadUrlForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetDownloadUrlForbidden(unwrapped)
}

// SetFake set fake values.
func (s *GetDownloadUrlNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetDownloadUrlNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetDownloadUrlUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetDownloadUrlUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *GetRootDirectoryNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetRootDirectoryNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetRootDirectoryUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetRootDirectoryUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemGroupNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemGroupNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemGroupUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemGroupUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemUserNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemUserNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetSystemUserUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetSystemUserUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *GetUserNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetUserNotFound(unwrapped)
}

// SetFake set fake values.
func (s *GetUserUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = GetUserUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *HandleCallbackBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = HandleCallbackBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *HandleCallbackUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = HandleCallbackUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *HealthStatus) SetFake() {
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.Version.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HealthStatusStatus) SetFake() {
	*s = HealthStatusStatusHealthy
}

// SetFake set fake values.
func (s *InitiateUploadBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = InitiateUploadBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *InitiateUploadForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = InitiateUploadForbidden(unwrapped)
}

// SetFake set fake values.
func (s *InitiateUploadRequest) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.ContentType.SetFake()
		}
	}
	{
		{
			s.Size = int64(0)
		}
	}
}

// SetFake set fake values.
func (s *InitiateUploadUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = InitiateUploadUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *Inode) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.SystemId = "string"
		}
	}
	{
		{
			s.Mode = int32(0)
		}
	}
	{
		{
			s.UID = int32(0)
		}
	}
	{
		{
			s.Gid = int32(0)
		}
	}
	{
		{
			s.Size = int64(0)
		}
	}
	{
		{
			s.LinkCount = int32(0)
		}
	}
	{
		{
			s.Flags = int32(0)
		}
	}
	{
		{
			s.Atime.SetFake()
		}
	}
	{
		{
			s.Mtime.SetFake()
		}
	}
	{
		{
			s.Ctime.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *InodeResponse) SetFake() {
	{
		{
			s.Inode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ListSystemGroupsNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ListSystemGroupsNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ListSystemGroupsUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ListSystemGroupsUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *ListSystemUsersNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ListSystemUsersNotFound(unwrapped)
}

// SetFake set fake values.
func (s *ListSystemUsersUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = ListSystemUsersUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *LoginResponse) SetFake() {
	{
		{
			s.AuthorizationUrl = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
		}
	}
	{
		{
			s.State = "string"
		}
	}
}

// SetFake set fake values.
func (s *LsForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = LsForbidden(unwrapped)
}

// SetFake set fake values.
func (s *LsNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = LsNotFound(unwrapped)
}

// SetFake set fake values.
func (s *LsUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = LsUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *MkdirBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MkdirBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *MkdirConflict) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MkdirConflict(unwrapped)
}

// SetFake set fake values.
func (s *MkdirForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MkdirForbidden(unwrapped)
}

// SetFake set fake values.
func (s *MkdirRequest) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Mode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *MkdirUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MkdirUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *MoveBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MoveBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *MoveConflict) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MoveConflict(unwrapped)
}

// SetFake set fake values.
func (s *MoveForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MoveForbidden(unwrapped)
}

// SetFake set fake values.
func (s *MoveNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MoveNotFound(unwrapped)
}

// SetFake set fake values.
func (s *MoveReq) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.Destination = "string"
		}
	}
}

// SetFake set fake values.
func (s *MoveUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = MoveUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *OptInt32) SetFake() {
	var elem int32
	{
		elem = int32(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilString) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptTimestamp) SetFake() {
	var elem Timestamp
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *Provider) SetFake() {
	*s = ProviderKeycloak
}

// SetFake set fake values.
func (s *RemoveGroupMemberNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RemoveGroupMemberNotFound(unwrapped)
}

// SetFake set fake values.
func (s *RemoveGroupMemberUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RemoveGroupMemberUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *RenameBadRequest) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RenameBadRequest(unwrapped)
}

// SetFake set fake values.
func (s *RenameConflict) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RenameConflict(unwrapped)
}

// SetFake set fake values.
func (s *RenameForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RenameForbidden(unwrapped)
}

// SetFake set fake values.
func (s *RenameNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RenameNotFound(unwrapped)
}

// SetFake set fake values.
func (s *RenameReq) SetFake() {
	{
		{
			s.Path = "string"
		}
	}
	{
		{
			s.NewName = "string"
		}
	}
}

// SetFake set fake values.
func (s *RenameUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = RenameUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *StatPathForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = StatPathForbidden(unwrapped)
}

// SetFake set fake values.
func (s *StatPathNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = StatPathNotFound(unwrapped)
}

// SetFake set fake values.
func (s *StatPathUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = StatPathUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *SymlinkRequest) SetFake() {
	{
		{
			s.Target = "string"
		}
	}
	{
		{
			s.LinkPath = "string"
		}
	}
}

// SetFake set fake values.
func (s *System) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Description.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SystemGroup) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.SystemId = "string"
		}
	}
	{
		{
			s.Name = "string"
		}
	}
	{
		{
			s.Gid = int32(0)
		}
	}
	{
		{
			s.Members = nil
			for i := 0; i < 0; i++ {
				var elem int64
				{
					elem = int64(0)
				}
				s.Members = append(s.Members, elem)
			}
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SystemGroupListResponse) SetFake() {
	{
		{
			s.Groups = nil
			for i := 0; i < 0; i++ {
				var elem SystemGroup
				{
					elem.SetFake()
				}
				s.Groups = append(s.Groups, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *SystemGroupResponse) SetFake() {
	{
		{
			s.Group.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SystemListResponse) SetFake() {
	{
		{
			s.Systems = nil
			for i := 0; i < 0; i++ {
				var elem System
				{
					elem.SetFake()
				}
				s.Systems = append(s.Systems, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *SystemResponse) SetFake() {
	{
		{
			s.System.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SystemStatus) SetFake() {
	*s = SystemStatusActive
}

// SetFake set fake values.
func (s *SystemUser) SetFake() {
	{
		{
			s.ID = int64(0)
		}
	}
	{
		{
			s.UserId = "string"
		}
	}
	{
		{
			s.SystemId = "string"
		}
	}
	{
		{
			s.Username = "string"
		}
	}
	{
		{
			s.UID = int32(0)
		}
	}
	{
		{
			s.Gid = int32(0)
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *SystemUserListResponse) SetFake() {
	{
		{
			s.Users = nil
			for i := 0; i < 0; i++ {
				var elem SystemUser
				{
					elem.SetFake()
				}
				s.Users = append(s.Users, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *SystemUserResponse) SetFake() {
	{
		{
			s.User.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Timestamp) SetFake() {
	var unwrapped time.Time
	{
		unwrapped = time.Now()
	}
	*s = Timestamp(unwrapped)
}

// SetFake set fake values.
func (s *UnlinkForbidden) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = UnlinkForbidden(unwrapped)
}

// SetFake set fake values.
func (s *UnlinkNotFound) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = UnlinkNotFound(unwrapped)
}

// SetFake set fake values.
func (s *UnlinkUnauthorized) SetFake() {
	var unwrapped Error
	{
		unwrapped.SetFake()
	}
	*s = UnlinkUnauthorized(unwrapped)
}

// SetFake set fake values.
func (s *UploadSession) SetFake() {
	{
		{
			s.ObjectId = "string"
		}
	}
	{
		{
			s.UploadUrl = url.URL{Scheme: "https", Host: "github.com", Path: "/ogen-go/ogen"}
		}
	}
	{
		{
			s.ExpiresAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UploadSessionResponse) SetFake() {
	{
		{
			s.UploadSession.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *User) SetFake() {
	{
		{
			s.ID = "string"
		}
	}
	{
		{
			s.Provider.SetFake()
		}
	}
	{
		{
			s.ProviderId = "string"
		}
	}
	{
		{
			s.JoinDate.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.UpdatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *UserResponse) SetFake() {
	{
		{
			s.User.SetFake()
		}
	}
}
