// Code generated by ogen, DO NOT EDIT.

package apiv1

import (
	"fmt"
	"net/url"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CallbackRequest
type CallbackRequest struct {
	// Authorization code from Keycloak.
	Code string `json:"code"`
	// OAuth state parameter.
	State string `json:"state"`
}

// GetCode returns the value of Code.
func (s *CallbackRequest) GetCode() string {
	return s.Code
}

// GetState returns the value of State.
func (s *CallbackRequest) GetState() string {
	return s.State
}

// SetCode sets the value of Code.
func (s *CallbackRequest) SetCode(val string) {
	s.Code = val
}

// SetState sets the value of State.
func (s *CallbackRequest) SetState(val string) {
	s.State = val
}

// Ref: #/components/schemas/CallbackResponse
type CallbackResponse struct {
	// Session ID for the authenticated user.
	SessionId string `json:"sessionId"`
	// User ID.
	UserId    int64        `json:"userId"`
	ExpiresAt OptTimestamp `json:"expiresAt"`
}

// GetSessionId returns the value of SessionId.
func (s *CallbackResponse) GetSessionId() string {
	return s.SessionId
}

// GetUserId returns the value of UserId.
func (s *CallbackResponse) GetUserId() int64 {
	return s.UserId
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *CallbackResponse) GetExpiresAt() OptTimestamp {
	return s.ExpiresAt
}

// SetSessionId sets the value of SessionId.
func (s *CallbackResponse) SetSessionId(val string) {
	s.SessionId = val
}

// SetUserId sets the value of UserId.
func (s *CallbackResponse) SetUserId(val int64) {
	s.UserId = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *CallbackResponse) SetExpiresAt(val OptTimestamp) {
	s.ExpiresAt = val
}

func (*CallbackResponse) handleCallbackRes() {}

type CompleteUploadBadRequest Error

func (*CompleteUploadBadRequest) completeUploadRes() {}

type CompleteUploadForbidden Error

func (*CompleteUploadForbidden) completeUploadRes() {}

type CompleteUploadNotFound Error

func (*CompleteUploadNotFound) completeUploadRes() {}

// Ref: #/components/schemas/CompleteUploadRequest
type CompleteUploadRequest struct {
	// Final file size in bytes.
	ByteSize OptInt64 `json:"byteSize"`
}

// GetByteSize returns the value of ByteSize.
func (s *CompleteUploadRequest) GetByteSize() OptInt64 {
	return s.ByteSize
}

// SetByteSize sets the value of ByteSize.
func (s *CompleteUploadRequest) SetByteSize(val OptInt64) {
	s.ByteSize = val
}

type CompleteUploadUnauthorized Error

func (*CompleteUploadUnauthorized) completeUploadRes() {}

type CopyFileBadRequest Error

func (*CopyFileBadRequest) copyFileRes() {}

type CopyFileForbidden Error

func (*CopyFileForbidden) copyFileRes() {}

type CopyFileNotFound Error

func (*CopyFileNotFound) copyFileRes() {}

// Ref: #/components/schemas/CopyFileRequest
type CopyFileRequest struct {
	// Target container file key.
	TargetKey uuid.UUID `json:"targetKey"`
}

// GetTargetKey returns the value of TargetKey.
func (s *CopyFileRequest) GetTargetKey() uuid.UUID {
	return s.TargetKey
}

// SetTargetKey sets the value of TargetKey.
func (s *CopyFileRequest) SetTargetKey(val uuid.UUID) {
	s.TargetKey = val
}

type CopyFileUnauthorized Error

func (*CopyFileUnauthorized) copyFileRes() {}

type CreateFileBadRequest Error

func (*CreateFileBadRequest) createFileRes() {}

type CreateFileForbidden Error

func (*CreateFileForbidden) createFileRes() {}

type CreateFileNotFound Error

func (*CreateFileNotFound) createFileRes() {}

// Ref: #/components/schemas/CreateFileRequest
type CreateFileRequest struct {
	Type FileType `json:"type"`
	// File name.
	FileName string `json:"fileName"`
	// Parent file key (container).
	ParentKey OptNilUUID `json:"parentKey"`
}

// GetType returns the value of Type.
func (s *CreateFileRequest) GetType() FileType {
	return s.Type
}

// GetFileName returns the value of FileName.
func (s *CreateFileRequest) GetFileName() string {
	return s.FileName
}

// GetParentKey returns the value of ParentKey.
func (s *CreateFileRequest) GetParentKey() OptNilUUID {
	return s.ParentKey
}

// SetType sets the value of Type.
func (s *CreateFileRequest) SetType(val FileType) {
	s.Type = val
}

// SetFileName sets the value of FileName.
func (s *CreateFileRequest) SetFileName(val string) {
	s.FileName = val
}

// SetParentKey sets the value of ParentKey.
func (s *CreateFileRequest) SetParentKey(val OptNilUUID) {
	s.ParentKey = val
}

type CreateFileUnauthorized Error

func (*CreateFileUnauthorized) createFileRes() {}

type CreateUserBadRequest Error

func (*CreateUserBadRequest) createUserRes() {}

type CreateUserConflict Error

func (*CreateUserConflict) createUserRes() {}

// Ref: #/components/schemas/CreateUserRequest
type CreateUserRequest struct {
	Provider Provider `json:"provider"`
	// User ID from the authentication provider.
	ProviderId string `json:"providerId"`
}

// GetProvider returns the value of Provider.
func (s *CreateUserRequest) GetProvider() Provider {
	return s.Provider
}

// GetProviderId returns the value of ProviderId.
func (s *CreateUserRequest) GetProviderId() string {
	return s.ProviderId
}

// SetProvider sets the value of Provider.
func (s *CreateUserRequest) SetProvider(val Provider) {
	s.Provider = val
}

// SetProviderId sets the value of ProviderId.
func (s *CreateUserRequest) SetProviderId(val string) {
	s.ProviderId = val
}

type DeleteFileForbidden Error

func (*DeleteFileForbidden) deleteFileRes() {}

// DeleteFileNoContent is response for DeleteFile operation.
type DeleteFileNoContent struct{}

func (*DeleteFileNoContent) deleteFileRes() {}

type DeleteFileNotFound Error

func (*DeleteFileNotFound) deleteFileRes() {}

type DeleteFileUnauthorized Error

func (*DeleteFileUnauthorized) deleteFileRes() {}

// DeleteUserNoContent is response for DeleteUser operation.
type DeleteUserNoContent struct{}

func (*DeleteUserNoContent) deleteUserRes() {}

type DeleteUserNotFound Error

func (*DeleteUserNotFound) deleteUserRes() {}

type DeleteUserUnauthorized Error

func (*DeleteUserUnauthorized) deleteUserRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Error ErrorError `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() ErrorError {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val ErrorError) {
	s.Error = val
}

func (*Error) logoutRes() {}

type ErrorError struct {
	// Error type.
	Type string `json:"type"`
	// Error message.
	Message string `json:"message"`
}

// GetType returns the value of Type.
func (s *ErrorError) GetType() string {
	return s.Type
}

// GetMessage returns the value of Message.
func (s *ErrorError) GetMessage() string {
	return s.Message
}

// SetType sets the value of Type.
func (s *ErrorError) SetType(val string) {
	s.Type = val
}

// SetMessage sets the value of Message.
func (s *ErrorError) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/File
type File struct {
	// File ID.
	ID int64 `json:"id"`
	// File UUID key.
	FileKey uuid.UUID `json:"fileKey"`
	Type    FileType  `json:"type"`
	// File name.
	FileName string `json:"fileName"`
	// Owner user ID.
	OwnerId OptInt64 `json:"ownerId"`
	// Parent file ID.
	ParentId OptNilInt64 `json:"parentId"`
	// File size in bytes.
	ByteSize  OptInt64     `json:"byteSize"`
	CreatedAt OptTimestamp `json:"createdAt"`
	UpdatedAt OptTimestamp `json:"updatedAt"`
	// Path from root to this file.
	Path []int64 `json:"path"`
	// Current user's roles for this file.
	Roles []string `json:"roles"`
}

// GetID returns the value of ID.
func (s *File) GetID() int64 {
	return s.ID
}

// GetFileKey returns the value of FileKey.
func (s *File) GetFileKey() uuid.UUID {
	return s.FileKey
}

// GetType returns the value of Type.
func (s *File) GetType() FileType {
	return s.Type
}

// GetFileName returns the value of FileName.
func (s *File) GetFileName() string {
	return s.FileName
}

// GetOwnerId returns the value of OwnerId.
func (s *File) GetOwnerId() OptInt64 {
	return s.OwnerId
}

// GetParentId returns the value of ParentId.
func (s *File) GetParentId() OptNilInt64 {
	return s.ParentId
}

// GetByteSize returns the value of ByteSize.
func (s *File) GetByteSize() OptInt64 {
	return s.ByteSize
}

// GetCreatedAt returns the value of CreatedAt.
func (s *File) GetCreatedAt() OptTimestamp {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *File) GetUpdatedAt() OptTimestamp {
	return s.UpdatedAt
}

// GetPath returns the value of Path.
func (s *File) GetPath() []int64 {
	return s.Path
}

// GetRoles returns the value of Roles.
func (s *File) GetRoles() []string {
	return s.Roles
}

// SetID sets the value of ID.
func (s *File) SetID(val int64) {
	s.ID = val
}

// SetFileKey sets the value of FileKey.
func (s *File) SetFileKey(val uuid.UUID) {
	s.FileKey = val
}

// SetType sets the value of Type.
func (s *File) SetType(val FileType) {
	s.Type = val
}

// SetFileName sets the value of FileName.
func (s *File) SetFileName(val string) {
	s.FileName = val
}

// SetOwnerId sets the value of OwnerId.
func (s *File) SetOwnerId(val OptInt64) {
	s.OwnerId = val
}

// SetParentId sets the value of ParentId.
func (s *File) SetParentId(val OptNilInt64) {
	s.ParentId = val
}

// SetByteSize sets the value of ByteSize.
func (s *File) SetByteSize(val OptInt64) {
	s.ByteSize = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *File) SetCreatedAt(val OptTimestamp) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *File) SetUpdatedAt(val OptTimestamp) {
	s.UpdatedAt = val
}

// SetPath sets the value of Path.
func (s *File) SetPath(val []int64) {
	s.Path = val
}

// SetRoles sets the value of Roles.
func (s *File) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/FileListResponse
type FileListResponse struct {
	Files []File `json:"files"`
}

// GetFiles returns the value of Files.
func (s *FileListResponse) GetFiles() []File {
	return s.Files
}

// SetFiles sets the value of Files.
func (s *FileListResponse) SetFiles(val []File) {
	s.Files = val
}

func (*FileListResponse) getFileChildrenRes() {}

// Ref: #/components/schemas/FileResponse
type FileResponse struct {
	File File `json:"file"`
}

// GetFile returns the value of File.
func (s *FileResponse) GetFile() File {
	return s.File
}

// SetFile sets the value of File.
func (s *FileResponse) SetFile(val File) {
	s.File = val
}

func (*FileResponse) completeUploadRes()    {}
func (*FileResponse) copyFileRes()          {}
func (*FileResponse) createFileRes()        {}
func (*FileResponse) getFileInfoRes()       {}
func (*FileResponse) getHomeContainerRes()  {}
func (*FileResponse) getRootContainerRes()  {}
func (*FileResponse) getTrashContainerRes() {}
func (*FileResponse) moveFileRes()          {}
func (*FileResponse) updateFileRes()        {}

// Type of file (container or file).
// Ref: #/components/schemas/FileType
type FileType string

const (
	FileTypeContainer FileType = "container"
	FileTypeFile      FileType = "file"
)

// AllValues returns all FileType values.
func (FileType) AllValues() []FileType {
	return []FileType{
		FileTypeContainer,
		FileTypeFile,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FileType) MarshalText() ([]byte, error) {
	switch s {
	case FileTypeContainer:
		return []byte(s), nil
	case FileTypeFile:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FileType) UnmarshalText(data []byte) error {
	switch FileType(data) {
	case FileTypeContainer:
		*s = FileTypeContainer
		return nil
	case FileTypeFile:
		*s = FileTypeFile
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type GetFileChildrenForbidden Error

func (*GetFileChildrenForbidden) getFileChildrenRes() {}

type GetFileChildrenNotFound Error

func (*GetFileChildrenNotFound) getFileChildrenRes() {}

type GetFileChildrenUnauthorized Error

func (*GetFileChildrenUnauthorized) getFileChildrenRes() {}

type GetFileInfoForbidden Error

func (*GetFileInfoForbidden) getFileInfoRes() {}

type GetFileInfoNotFound Error

func (*GetFileInfoNotFound) getFileInfoRes() {}

type GetFileInfoUnauthorized Error

func (*GetFileInfoUnauthorized) getFileInfoRes() {}

type GetHomeContainerNotFound Error

func (*GetHomeContainerNotFound) getHomeContainerRes() {}

type GetHomeContainerUnauthorized Error

func (*GetHomeContainerUnauthorized) getHomeContainerRes() {}

type GetRootContainerNotFound Error

func (*GetRootContainerNotFound) getRootContainerRes() {}

type GetRootContainerUnauthorized Error

func (*GetRootContainerUnauthorized) getRootContainerRes() {}

type GetServiceStatusNotFound Error

func (*GetServiceStatusNotFound) getServiceStatusRes() {}

type GetServiceStatusUnauthorized Error

func (*GetServiceStatusUnauthorized) getServiceStatusRes() {}

type GetStreamTokenForbidden Error

func (*GetStreamTokenForbidden) getStreamTokenRes() {}

type GetStreamTokenNotFound Error

func (*GetStreamTokenNotFound) getStreamTokenRes() {}

type GetStreamTokenUnauthorized Error

func (*GetStreamTokenUnauthorized) getStreamTokenRes() {}

type GetTrashContainerNotFound Error

func (*GetTrashContainerNotFound) getTrashContainerRes() {}

type GetTrashContainerUnauthorized Error

func (*GetTrashContainerUnauthorized) getTrashContainerRes() {}

type GetUploadTokenForbidden Error

func (*GetUploadTokenForbidden) getUploadTokenRes() {}

type GetUploadTokenNotFound Error

func (*GetUploadTokenNotFound) getUploadTokenRes() {}

type GetUploadTokenUnauthorized Error

func (*GetUploadTokenUnauthorized) getUploadTokenRes() {}

type GetUserNotFound Error

func (*GetUserNotFound) getUserRes() {}

type GetUserUnauthorized Error

func (*GetUserUnauthorized) getUserRes() {}

type HandleCallbackBadRequest Error

func (*HandleCallbackBadRequest) handleCallbackRes() {}

type HandleCallbackUnauthorized Error

func (*HandleCallbackUnauthorized) handleCallbackRes() {}

// Ref: #/components/schemas/HealthStatus
type HealthStatus struct {
	// Health status.
	Status HealthStatusStatus `json:"status"`
	// Application version.
	Version OptString `json:"version"`
}

// GetStatus returns the value of Status.
func (s *HealthStatus) GetStatus() HealthStatusStatus {
	return s.Status
}

// GetVersion returns the value of Version.
func (s *HealthStatus) GetVersion() OptString {
	return s.Version
}

// SetStatus sets the value of Status.
func (s *HealthStatus) SetStatus(val HealthStatusStatus) {
	s.Status = val
}

// SetVersion sets the value of Version.
func (s *HealthStatus) SetVersion(val OptString) {
	s.Version = val
}

// Health status.
type HealthStatusStatus string

const (
	HealthStatusStatusHealthy   HealthStatusStatus = "healthy"
	HealthStatusStatusUnhealthy HealthStatusStatus = "unhealthy"
)

// AllValues returns all HealthStatusStatus values.
func (HealthStatusStatus) AllValues() []HealthStatusStatus {
	return []HealthStatusStatus{
		HealthStatusStatusHealthy,
		HealthStatusStatusUnhealthy,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatusStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusStatusHealthy:
		return []byte(s), nil
	case HealthStatusStatusUnhealthy:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatusStatus) UnmarshalText(data []byte) error {
	switch HealthStatusStatus(data) {
	case HealthStatusStatusHealthy:
		*s = HealthStatusStatusHealthy
		return nil
	case HealthStatusStatusUnhealthy:
		*s = HealthStatusStatusUnhealthy
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/LoginResponse
type LoginResponse struct {
	// Keycloak authorization URL.
	AuthorizationUrl url.URL `json:"authorizationUrl"`
	// OAuth state parameter.
	State string `json:"state"`
}

// GetAuthorizationUrl returns the value of AuthorizationUrl.
func (s *LoginResponse) GetAuthorizationUrl() url.URL {
	return s.AuthorizationUrl
}

// GetState returns the value of State.
func (s *LoginResponse) GetState() string {
	return s.State
}

// SetAuthorizationUrl sets the value of AuthorizationUrl.
func (s *LoginResponse) SetAuthorizationUrl(val url.URL) {
	s.AuthorizationUrl = val
}

// SetState sets the value of State.
func (s *LoginResponse) SetState(val string) {
	s.State = val
}

// LogoutNoContent is response for Logout operation.
type LogoutNoContent struct{}

func (*LogoutNoContent) logoutRes() {}

type MoveFileBadRequest Error

func (*MoveFileBadRequest) moveFileRes() {}

type MoveFileForbidden Error

func (*MoveFileForbidden) moveFileRes() {}

type MoveFileNotFound Error

func (*MoveFileNotFound) moveFileRes() {}

// Ref: #/components/schemas/MoveFileRequest
type MoveFileRequest struct {
	// Target container file key.
	TargetKey uuid.UUID `json:"targetKey"`
}

// GetTargetKey returns the value of TargetKey.
func (s *MoveFileRequest) GetTargetKey() uuid.UUID {
	return s.TargetKey
}

// SetTargetKey sets the value of TargetKey.
func (s *MoveFileRequest) SetTargetKey(val uuid.UUID) {
	s.TargetKey = val
}

type MoveFileUnauthorized Error

func (*MoveFileUnauthorized) moveFileRes() {}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompleteUploadRequest returns new OptCompleteUploadRequest with value set to v.
func NewOptCompleteUploadRequest(v CompleteUploadRequest) OptCompleteUploadRequest {
	return OptCompleteUploadRequest{
		Value: v,
		Set:   true,
	}
}

// OptCompleteUploadRequest is optional CompleteUploadRequest.
type OptCompleteUploadRequest struct {
	Value CompleteUploadRequest
	Set   bool
}

// IsSet returns true if OptCompleteUploadRequest was set.
func (o OptCompleteUploadRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompleteUploadRequest) Reset() {
	var v CompleteUploadRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompleteUploadRequest) SetTo(v CompleteUploadRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompleteUploadRequest) Get() (v CompleteUploadRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompleteUploadRequest) Or(d CompleteUploadRequest) CompleteUploadRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64 returns new OptNilInt64 with value set to v.
func NewOptNilInt64(v int64) OptNilInt64 {
	return OptNilInt64{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64 is optional nullable int64.
type OptNilInt64 struct {
	Value int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64 was set.
func (o OptNilInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64) SetTo(v int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt64) SetToNull() {
	o.Set = true
	o.Null = true
	var v int64
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTimestamp returns new OptTimestamp with value set to v.
func NewOptTimestamp(v Timestamp) OptTimestamp {
	return OptTimestamp{
		Value: v,
		Set:   true,
	}
}

// OptTimestamp is optional Timestamp.
type OptTimestamp struct {
	Value Timestamp
	Set   bool
}

// IsSet returns true if OptTimestamp was set.
func (o OptTimestamp) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTimestamp) Reset() {
	var v Timestamp
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTimestamp) SetTo(v Timestamp) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTimestamp) Get() (v Timestamp, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTimestamp) Or(d Timestamp) Timestamp {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Authentication provider.
// Ref: #/components/schemas/Provider
type Provider string

const (
	ProviderKeycloak Provider = "keycloak"
	ProviderGoogle   Provider = "google"
)

// AllValues returns all Provider values.
func (Provider) AllValues() []Provider {
	return []Provider{
		ProviderKeycloak,
		ProviderGoogle,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s Provider) MarshalText() ([]byte, error) {
	switch s {
	case ProviderKeycloak:
		return []byte(s), nil
	case ProviderGoogle:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *Provider) UnmarshalText(data []byte) error {
	switch Provider(data) {
	case ProviderKeycloak:
		*s = ProviderKeycloak
		return nil
	case ProviderGoogle:
		*s = ProviderGoogle
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ServiceStatus
type ServiceStatus struct {
	// User ID.
	UserId int64 `json:"userId"`
	// Service availability status.
	Available  bool         `json:"available"`
	JoinDate   OptTimestamp `json:"joinDate"`
	UpdateDate OptTimestamp `json:"updateDate"`
}

// GetUserId returns the value of UserId.
func (s *ServiceStatus) GetUserId() int64 {
	return s.UserId
}

// GetAvailable returns the value of Available.
func (s *ServiceStatus) GetAvailable() bool {
	return s.Available
}

// GetJoinDate returns the value of JoinDate.
func (s *ServiceStatus) GetJoinDate() OptTimestamp {
	return s.JoinDate
}

// GetUpdateDate returns the value of UpdateDate.
func (s *ServiceStatus) GetUpdateDate() OptTimestamp {
	return s.UpdateDate
}

// SetUserId sets the value of UserId.
func (s *ServiceStatus) SetUserId(val int64) {
	s.UserId = val
}

// SetAvailable sets the value of Available.
func (s *ServiceStatus) SetAvailable(val bool) {
	s.Available = val
}

// SetJoinDate sets the value of JoinDate.
func (s *ServiceStatus) SetJoinDate(val OptTimestamp) {
	s.JoinDate = val
}

// SetUpdateDate sets the value of UpdateDate.
func (s *ServiceStatus) SetUpdateDate(val OptTimestamp) {
	s.UpdateDate = val
}

// Ref: #/components/schemas/ServiceStatusResponse
type ServiceStatusResponse struct {
	Status ServiceStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *ServiceStatusResponse) GetStatus() ServiceStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *ServiceStatusResponse) SetStatus(val ServiceStatus) {
	s.Status = val
}

func (*ServiceStatusResponse) getServiceStatusRes() {}

type SessionAuth struct {
	APIKey string
	Roles  []string
}

// GetAPIKey returns the value of APIKey.
func (s *SessionAuth) GetAPIKey() string {
	return s.APIKey
}

// GetRoles returns the value of Roles.
func (s *SessionAuth) GetRoles() []string {
	return s.Roles
}

// SetAPIKey sets the value of APIKey.
func (s *SessionAuth) SetAPIKey(val string) {
	s.APIKey = val
}

// SetRoles sets the value of Roles.
func (s *SessionAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/StreamToken
type StreamToken struct {
	// Stream token.
	Token string `json:"token"`
	// Presigned S3 download URL.
	DownloadUrl url.URL   `json:"downloadUrl"`
	ExpiresAt   Timestamp `json:"expiresAt"`
}

// GetToken returns the value of Token.
func (s *StreamToken) GetToken() string {
	return s.Token
}

// GetDownloadUrl returns the value of DownloadUrl.
func (s *StreamToken) GetDownloadUrl() url.URL {
	return s.DownloadUrl
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *StreamToken) GetExpiresAt() Timestamp {
	return s.ExpiresAt
}

// SetToken sets the value of Token.
func (s *StreamToken) SetToken(val string) {
	s.Token = val
}

// SetDownloadUrl sets the value of DownloadUrl.
func (s *StreamToken) SetDownloadUrl(val url.URL) {
	s.DownloadUrl = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *StreamToken) SetExpiresAt(val Timestamp) {
	s.ExpiresAt = val
}

// Ref: #/components/schemas/StreamTokenResponse
type StreamTokenResponse struct {
	StreamToken StreamToken `json:"streamToken"`
}

// GetStreamToken returns the value of StreamToken.
func (s *StreamTokenResponse) GetStreamToken() StreamToken {
	return s.StreamToken
}

// SetStreamToken sets the value of StreamToken.
func (s *StreamTokenResponse) SetStreamToken(val StreamToken) {
	s.StreamToken = val
}

func (*StreamTokenResponse) getStreamTokenRes() {}

type Timestamp time.Time

type UpdateFileBadRequest Error

func (*UpdateFileBadRequest) updateFileRes() {}

type UpdateFileForbidden Error

func (*UpdateFileForbidden) updateFileRes() {}

type UpdateFileNotFound Error

func (*UpdateFileNotFound) updateFileRes() {}

// Ref: #/components/schemas/UpdateFileRequest
type UpdateFileRequest struct {
	// New file name.
	FileName OptString `json:"fileName"`
}

// GetFileName returns the value of FileName.
func (s *UpdateFileRequest) GetFileName() OptString {
	return s.FileName
}

// SetFileName sets the value of FileName.
func (s *UpdateFileRequest) SetFileName(val OptString) {
	s.FileName = val
}

type UpdateFileUnauthorized Error

func (*UpdateFileUnauthorized) updateFileRes() {}

// Ref: #/components/schemas/UploadToken
type UploadToken struct {
	// Upload token for tracking.
	Token string `json:"token"`
	// Presigned S3 upload URL.
	UploadUrl url.URL   `json:"uploadUrl"`
	ExpiresAt Timestamp `json:"expiresAt"`
}

// GetToken returns the value of Token.
func (s *UploadToken) GetToken() string {
	return s.Token
}

// GetUploadUrl returns the value of UploadUrl.
func (s *UploadToken) GetUploadUrl() url.URL {
	return s.UploadUrl
}

// GetExpiresAt returns the value of ExpiresAt.
func (s *UploadToken) GetExpiresAt() Timestamp {
	return s.ExpiresAt
}

// SetToken sets the value of Token.
func (s *UploadToken) SetToken(val string) {
	s.Token = val
}

// SetUploadUrl sets the value of UploadUrl.
func (s *UploadToken) SetUploadUrl(val url.URL) {
	s.UploadUrl = val
}

// SetExpiresAt sets the value of ExpiresAt.
func (s *UploadToken) SetExpiresAt(val Timestamp) {
	s.ExpiresAt = val
}

// Ref: #/components/schemas/UploadTokenResponse
type UploadTokenResponse struct {
	UploadToken UploadToken `json:"uploadToken"`
}

// GetUploadToken returns the value of UploadToken.
func (s *UploadTokenResponse) GetUploadToken() UploadToken {
	return s.UploadToken
}

// SetUploadToken sets the value of UploadToken.
func (s *UploadTokenResponse) SetUploadToken(val UploadToken) {
	s.UploadToken = val
}

func (*UploadTokenResponse) getUploadTokenRes() {}

// Ref: #/components/schemas/User
type User struct {
	// User ID.
	ID       int64    `json:"id"`
	Provider Provider `json:"provider"`
	// User ID from the authentication provider.
	ProviderId string       `json:"providerId"`
	CreatedAt  OptTimestamp `json:"createdAt"`
	UpdatedAt  OptTimestamp `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *User) GetID() int64 {
	return s.ID
}

// GetProvider returns the value of Provider.
func (s *User) GetProvider() Provider {
	return s.Provider
}

// GetProviderId returns the value of ProviderId.
func (s *User) GetProviderId() string {
	return s.ProviderId
}

// GetCreatedAt returns the value of CreatedAt.
func (s *User) GetCreatedAt() OptTimestamp {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *User) GetUpdatedAt() OptTimestamp {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *User) SetID(val int64) {
	s.ID = val
}

// SetProvider sets the value of Provider.
func (s *User) SetProvider(val Provider) {
	s.Provider = val
}

// SetProviderId sets the value of ProviderId.
func (s *User) SetProviderId(val string) {
	s.ProviderId = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *User) SetCreatedAt(val OptTimestamp) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *User) SetUpdatedAt(val OptTimestamp) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/UserResponse
type UserResponse struct {
	User User `json:"user"`
}

// GetUser returns the value of User.
func (s *UserResponse) GetUser() User {
	return s.User
}

// SetUser sets the value of User.
func (s *UserResponse) SetUser(val User) {
	s.User = val
}

func (*UserResponse) createUserRes() {}
func (*UserResponse) getUserRes()    {}
