// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/starfrag-lab/retrowin-go/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/starfrag-lab/retrowin-go/ent/file"
	"github.com/starfrag-lab/retrowin-go/ent/fileinfo"
	"github.com/starfrag-lab/retrowin-go/ent/filelink"
	"github.com/starfrag-lab/retrowin-go/ent/filepath"
	"github.com/starfrag-lab/retrowin-go/ent/filerole"
	"github.com/starfrag-lab/retrowin-go/ent/servicestatus"
	"github.com/starfrag-lab/retrowin-go/ent/tempfile"
	"github.com/starfrag-lab/retrowin-go/ent/user"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// File is the client for interacting with the File builders.
	File *FileClient
	// FileInfo is the client for interacting with the FileInfo builders.
	FileInfo *FileInfoClient
	// FileLink is the client for interacting with the FileLink builders.
	FileLink *FileLinkClient
	// FilePath is the client for interacting with the FilePath builders.
	FilePath *FilePathClient
	// FileRole is the client for interacting with the FileRole builders.
	FileRole *FileRoleClient
	// ServiceStatus is the client for interacting with the ServiceStatus builders.
	ServiceStatus *ServiceStatusClient
	// TempFile is the client for interacting with the TempFile builders.
	TempFile *TempFileClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.File = NewFileClient(c.config)
	c.FileInfo = NewFileInfoClient(c.config)
	c.FileLink = NewFileLinkClient(c.config)
	c.FilePath = NewFilePathClient(c.config)
	c.FileRole = NewFileRoleClient(c.config)
	c.ServiceStatus = NewServiceStatusClient(c.config)
	c.TempFile = NewTempFileClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		File:          NewFileClient(cfg),
		FileInfo:      NewFileInfoClient(cfg),
		FileLink:      NewFileLinkClient(cfg),
		FilePath:      NewFilePathClient(cfg),
		FileRole:      NewFileRoleClient(cfg),
		ServiceStatus: NewServiceStatusClient(cfg),
		TempFile:      NewTempFileClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		File:          NewFileClient(cfg),
		FileInfo:      NewFileInfoClient(cfg),
		FileLink:      NewFileLinkClient(cfg),
		FilePath:      NewFilePathClient(cfg),
		FileRole:      NewFileRoleClient(cfg),
		ServiceStatus: NewServiceStatusClient(cfg),
		TempFile:      NewTempFileClient(cfg),
		User:          NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		File.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.File, c.FileInfo, c.FileLink, c.FilePath, c.FileRole, c.ServiceStatus,
		c.TempFile, c.User,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.File, c.FileInfo, c.FileLink, c.FilePath, c.FileRole, c.ServiceStatus,
		c.TempFile, c.User,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FileMutation:
		return c.File.mutate(ctx, m)
	case *FileInfoMutation:
		return c.FileInfo.mutate(ctx, m)
	case *FileLinkMutation:
		return c.FileLink.mutate(ctx, m)
	case *FilePathMutation:
		return c.FilePath.mutate(ctx, m)
	case *FileRoleMutation:
		return c.FileRole.mutate(ctx, m)
	case *ServiceStatusMutation:
		return c.ServiceStatus.mutate(ctx, m)
	case *TempFileMutation:
		return c.TempFile.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FileClient is a client for the File schema.
type FileClient struct {
	config
}

// NewFileClient returns a client for the File from the given config.
func NewFileClient(c config) *FileClient {
	return &FileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `file.Hooks(f(g(h())))`.
func (c *FileClient) Use(hooks ...Hook) {
	c.hooks.File = append(c.hooks.File, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `file.Intercept(f(g(h())))`.
func (c *FileClient) Intercept(interceptors ...Interceptor) {
	c.inters.File = append(c.inters.File, interceptors...)
}

// Create returns a builder for creating a File entity.
func (c *FileClient) Create() *FileCreate {
	mutation := newFileMutation(c.config, OpCreate)
	return &FileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of File entities.
func (c *FileClient) CreateBulk(builders ...*FileCreate) *FileCreateBulk {
	return &FileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileClient) MapCreateBulk(slice any, setFunc func(*FileCreate, int)) *FileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileCreateBulk{err: fmt.Errorf("calling to FileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for File.
func (c *FileClient) Update() *FileUpdate {
	mutation := newFileMutation(c.config, OpUpdate)
	return &FileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileClient) UpdateOne(_m *File) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFile(_m))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileClient) UpdateOneID(id int) *FileUpdateOne {
	mutation := newFileMutation(c.config, OpUpdateOne, withFileID(id))
	return &FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for File.
func (c *FileClient) Delete() *FileDelete {
	mutation := newFileMutation(c.config, OpDelete)
	return &FileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileClient) DeleteOne(_m *File) *FileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileClient) DeleteOneID(id int) *FileDeleteOne {
	builder := c.Delete().Where(file.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileDeleteOne{builder}
}

// Query returns a query builder for File.
func (c *FileClient) Query() *FileQuery {
	return &FileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFile},
		inters: c.Interceptors(),
	}
}

// Get returns a File entity by its id.
func (c *FileClient) Get(ctx context.Context, id int) (*File, error) {
	return c.Query().Where(file.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileClient) GetX(ctx context.Context, id int) *File {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FileClient) Hooks() []Hook {
	return c.hooks.File
}

// Interceptors returns the client interceptors.
func (c *FileClient) Interceptors() []Interceptor {
	return c.inters.File
}

func (c *FileClient) mutate(ctx context.Context, m *FileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown File mutation op: %q", m.Op())
	}
}

// FileInfoClient is a client for the FileInfo schema.
type FileInfoClient struct {
	config
}

// NewFileInfoClient returns a client for the FileInfo from the given config.
func NewFileInfoClient(c config) *FileInfoClient {
	return &FileInfoClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fileinfo.Hooks(f(g(h())))`.
func (c *FileInfoClient) Use(hooks ...Hook) {
	c.hooks.FileInfo = append(c.hooks.FileInfo, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fileinfo.Intercept(f(g(h())))`.
func (c *FileInfoClient) Intercept(interceptors ...Interceptor) {
	c.inters.FileInfo = append(c.inters.FileInfo, interceptors...)
}

// Create returns a builder for creating a FileInfo entity.
func (c *FileInfoClient) Create() *FileInfoCreate {
	mutation := newFileInfoMutation(c.config, OpCreate)
	return &FileInfoCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FileInfo entities.
func (c *FileInfoClient) CreateBulk(builders ...*FileInfoCreate) *FileInfoCreateBulk {
	return &FileInfoCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileInfoClient) MapCreateBulk(slice any, setFunc func(*FileInfoCreate, int)) *FileInfoCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileInfoCreateBulk{err: fmt.Errorf("calling to FileInfoClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileInfoCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileInfoCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FileInfo.
func (c *FileInfoClient) Update() *FileInfoUpdate {
	mutation := newFileInfoMutation(c.config, OpUpdate)
	return &FileInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileInfoClient) UpdateOne(_m *FileInfo) *FileInfoUpdateOne {
	mutation := newFileInfoMutation(c.config, OpUpdateOne, withFileInfo(_m))
	return &FileInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileInfoClient) UpdateOneID(id int) *FileInfoUpdateOne {
	mutation := newFileInfoMutation(c.config, OpUpdateOne, withFileInfoID(id))
	return &FileInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FileInfo.
func (c *FileInfoClient) Delete() *FileInfoDelete {
	mutation := newFileInfoMutation(c.config, OpDelete)
	return &FileInfoDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileInfoClient) DeleteOne(_m *FileInfo) *FileInfoDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileInfoClient) DeleteOneID(id int) *FileInfoDeleteOne {
	builder := c.Delete().Where(fileinfo.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileInfoDeleteOne{builder}
}

// Query returns a query builder for FileInfo.
func (c *FileInfoClient) Query() *FileInfoQuery {
	return &FileInfoQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFileInfo},
		inters: c.Interceptors(),
	}
}

// Get returns a FileInfo entity by its id.
func (c *FileInfoClient) Get(ctx context.Context, id int) (*FileInfo, error) {
	return c.Query().Where(fileinfo.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileInfoClient) GetX(ctx context.Context, id int) *FileInfo {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FileInfoClient) Hooks() []Hook {
	return c.hooks.FileInfo
}

// Interceptors returns the client interceptors.
func (c *FileInfoClient) Interceptors() []Interceptor {
	return c.inters.FileInfo
}

func (c *FileInfoClient) mutate(ctx context.Context, m *FileInfoMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileInfoCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileInfoUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileInfoUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileInfoDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FileInfo mutation op: %q", m.Op())
	}
}

// FileLinkClient is a client for the FileLink schema.
type FileLinkClient struct {
	config
}

// NewFileLinkClient returns a client for the FileLink from the given config.
func NewFileLinkClient(c config) *FileLinkClient {
	return &FileLinkClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `filelink.Hooks(f(g(h())))`.
func (c *FileLinkClient) Use(hooks ...Hook) {
	c.hooks.FileLink = append(c.hooks.FileLink, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `filelink.Intercept(f(g(h())))`.
func (c *FileLinkClient) Intercept(interceptors ...Interceptor) {
	c.inters.FileLink = append(c.inters.FileLink, interceptors...)
}

// Create returns a builder for creating a FileLink entity.
func (c *FileLinkClient) Create() *FileLinkCreate {
	mutation := newFileLinkMutation(c.config, OpCreate)
	return &FileLinkCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FileLink entities.
func (c *FileLinkClient) CreateBulk(builders ...*FileLinkCreate) *FileLinkCreateBulk {
	return &FileLinkCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileLinkClient) MapCreateBulk(slice any, setFunc func(*FileLinkCreate, int)) *FileLinkCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileLinkCreateBulk{err: fmt.Errorf("calling to FileLinkClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileLinkCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileLinkCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FileLink.
func (c *FileLinkClient) Update() *FileLinkUpdate {
	mutation := newFileLinkMutation(c.config, OpUpdate)
	return &FileLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileLinkClient) UpdateOne(_m *FileLink) *FileLinkUpdateOne {
	mutation := newFileLinkMutation(c.config, OpUpdateOne, withFileLink(_m))
	return &FileLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileLinkClient) UpdateOneID(id int) *FileLinkUpdateOne {
	mutation := newFileLinkMutation(c.config, OpUpdateOne, withFileLinkID(id))
	return &FileLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FileLink.
func (c *FileLinkClient) Delete() *FileLinkDelete {
	mutation := newFileLinkMutation(c.config, OpDelete)
	return &FileLinkDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileLinkClient) DeleteOne(_m *FileLink) *FileLinkDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileLinkClient) DeleteOneID(id int) *FileLinkDeleteOne {
	builder := c.Delete().Where(filelink.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileLinkDeleteOne{builder}
}

// Query returns a query builder for FileLink.
func (c *FileLinkClient) Query() *FileLinkQuery {
	return &FileLinkQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFileLink},
		inters: c.Interceptors(),
	}
}

// Get returns a FileLink entity by its id.
func (c *FileLinkClient) Get(ctx context.Context, id int) (*FileLink, error) {
	return c.Query().Where(filelink.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileLinkClient) GetX(ctx context.Context, id int) *FileLink {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FileLinkClient) Hooks() []Hook {
	return c.hooks.FileLink
}

// Interceptors returns the client interceptors.
func (c *FileLinkClient) Interceptors() []Interceptor {
	return c.inters.FileLink
}

func (c *FileLinkClient) mutate(ctx context.Context, m *FileLinkMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileLinkCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileLinkUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileLinkUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileLinkDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FileLink mutation op: %q", m.Op())
	}
}

// FilePathClient is a client for the FilePath schema.
type FilePathClient struct {
	config
}

// NewFilePathClient returns a client for the FilePath from the given config.
func NewFilePathClient(c config) *FilePathClient {
	return &FilePathClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `filepath.Hooks(f(g(h())))`.
func (c *FilePathClient) Use(hooks ...Hook) {
	c.hooks.FilePath = append(c.hooks.FilePath, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `filepath.Intercept(f(g(h())))`.
func (c *FilePathClient) Intercept(interceptors ...Interceptor) {
	c.inters.FilePath = append(c.inters.FilePath, interceptors...)
}

// Create returns a builder for creating a FilePath entity.
func (c *FilePathClient) Create() *FilePathCreate {
	mutation := newFilePathMutation(c.config, OpCreate)
	return &FilePathCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FilePath entities.
func (c *FilePathClient) CreateBulk(builders ...*FilePathCreate) *FilePathCreateBulk {
	return &FilePathCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FilePathClient) MapCreateBulk(slice any, setFunc func(*FilePathCreate, int)) *FilePathCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FilePathCreateBulk{err: fmt.Errorf("calling to FilePathClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FilePathCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FilePathCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FilePath.
func (c *FilePathClient) Update() *FilePathUpdate {
	mutation := newFilePathMutation(c.config, OpUpdate)
	return &FilePathUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FilePathClient) UpdateOne(_m *FilePath) *FilePathUpdateOne {
	mutation := newFilePathMutation(c.config, OpUpdateOne, withFilePath(_m))
	return &FilePathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FilePathClient) UpdateOneID(id int) *FilePathUpdateOne {
	mutation := newFilePathMutation(c.config, OpUpdateOne, withFilePathID(id))
	return &FilePathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FilePath.
func (c *FilePathClient) Delete() *FilePathDelete {
	mutation := newFilePathMutation(c.config, OpDelete)
	return &FilePathDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FilePathClient) DeleteOne(_m *FilePath) *FilePathDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FilePathClient) DeleteOneID(id int) *FilePathDeleteOne {
	builder := c.Delete().Where(filepath.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FilePathDeleteOne{builder}
}

// Query returns a query builder for FilePath.
func (c *FilePathClient) Query() *FilePathQuery {
	return &FilePathQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFilePath},
		inters: c.Interceptors(),
	}
}

// Get returns a FilePath entity by its id.
func (c *FilePathClient) Get(ctx context.Context, id int) (*FilePath, error) {
	return c.Query().Where(filepath.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FilePathClient) GetX(ctx context.Context, id int) *FilePath {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FilePathClient) Hooks() []Hook {
	return c.hooks.FilePath
}

// Interceptors returns the client interceptors.
func (c *FilePathClient) Interceptors() []Interceptor {
	return c.inters.FilePath
}

func (c *FilePathClient) mutate(ctx context.Context, m *FilePathMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FilePathCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FilePathUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FilePathUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FilePathDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FilePath mutation op: %q", m.Op())
	}
}

// FileRoleClient is a client for the FileRole schema.
type FileRoleClient struct {
	config
}

// NewFileRoleClient returns a client for the FileRole from the given config.
func NewFileRoleClient(c config) *FileRoleClient {
	return &FileRoleClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `filerole.Hooks(f(g(h())))`.
func (c *FileRoleClient) Use(hooks ...Hook) {
	c.hooks.FileRole = append(c.hooks.FileRole, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `filerole.Intercept(f(g(h())))`.
func (c *FileRoleClient) Intercept(interceptors ...Interceptor) {
	c.inters.FileRole = append(c.inters.FileRole, interceptors...)
}

// Create returns a builder for creating a FileRole entity.
func (c *FileRoleClient) Create() *FileRoleCreate {
	mutation := newFileRoleMutation(c.config, OpCreate)
	return &FileRoleCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of FileRole entities.
func (c *FileRoleClient) CreateBulk(builders ...*FileRoleCreate) *FileRoleCreateBulk {
	return &FileRoleCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FileRoleClient) MapCreateBulk(slice any, setFunc func(*FileRoleCreate, int)) *FileRoleCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FileRoleCreateBulk{err: fmt.Errorf("calling to FileRoleClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FileRoleCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FileRoleCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for FileRole.
func (c *FileRoleClient) Update() *FileRoleUpdate {
	mutation := newFileRoleMutation(c.config, OpUpdate)
	return &FileRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FileRoleClient) UpdateOne(_m *FileRole) *FileRoleUpdateOne {
	mutation := newFileRoleMutation(c.config, OpUpdateOne, withFileRole(_m))
	return &FileRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FileRoleClient) UpdateOneID(id int) *FileRoleUpdateOne {
	mutation := newFileRoleMutation(c.config, OpUpdateOne, withFileRoleID(id))
	return &FileRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for FileRole.
func (c *FileRoleClient) Delete() *FileRoleDelete {
	mutation := newFileRoleMutation(c.config, OpDelete)
	return &FileRoleDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FileRoleClient) DeleteOne(_m *FileRole) *FileRoleDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FileRoleClient) DeleteOneID(id int) *FileRoleDeleteOne {
	builder := c.Delete().Where(filerole.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FileRoleDeleteOne{builder}
}

// Query returns a query builder for FileRole.
func (c *FileRoleClient) Query() *FileRoleQuery {
	return &FileRoleQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFileRole},
		inters: c.Interceptors(),
	}
}

// Get returns a FileRole entity by its id.
func (c *FileRoleClient) Get(ctx context.Context, id int) (*FileRole, error) {
	return c.Query().Where(filerole.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FileRoleClient) GetX(ctx context.Context, id int) *FileRole {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FileRoleClient) Hooks() []Hook {
	return c.hooks.FileRole
}

// Interceptors returns the client interceptors.
func (c *FileRoleClient) Interceptors() []Interceptor {
	return c.inters.FileRole
}

func (c *FileRoleClient) mutate(ctx context.Context, m *FileRoleMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FileRoleCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FileRoleUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FileRoleUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FileRoleDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown FileRole mutation op: %q", m.Op())
	}
}

// ServiceStatusClient is a client for the ServiceStatus schema.
type ServiceStatusClient struct {
	config
}

// NewServiceStatusClient returns a client for the ServiceStatus from the given config.
func NewServiceStatusClient(c config) *ServiceStatusClient {
	return &ServiceStatusClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `servicestatus.Hooks(f(g(h())))`.
func (c *ServiceStatusClient) Use(hooks ...Hook) {
	c.hooks.ServiceStatus = append(c.hooks.ServiceStatus, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `servicestatus.Intercept(f(g(h())))`.
func (c *ServiceStatusClient) Intercept(interceptors ...Interceptor) {
	c.inters.ServiceStatus = append(c.inters.ServiceStatus, interceptors...)
}

// Create returns a builder for creating a ServiceStatus entity.
func (c *ServiceStatusClient) Create() *ServiceStatusCreate {
	mutation := newServiceStatusMutation(c.config, OpCreate)
	return &ServiceStatusCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of ServiceStatus entities.
func (c *ServiceStatusClient) CreateBulk(builders ...*ServiceStatusCreate) *ServiceStatusCreateBulk {
	return &ServiceStatusCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ServiceStatusClient) MapCreateBulk(slice any, setFunc func(*ServiceStatusCreate, int)) *ServiceStatusCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ServiceStatusCreateBulk{err: fmt.Errorf("calling to ServiceStatusClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ServiceStatusCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ServiceStatusCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for ServiceStatus.
func (c *ServiceStatusClient) Update() *ServiceStatusUpdate {
	mutation := newServiceStatusMutation(c.config, OpUpdate)
	return &ServiceStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ServiceStatusClient) UpdateOne(_m *ServiceStatus) *ServiceStatusUpdateOne {
	mutation := newServiceStatusMutation(c.config, OpUpdateOne, withServiceStatus(_m))
	return &ServiceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ServiceStatusClient) UpdateOneID(id int) *ServiceStatusUpdateOne {
	mutation := newServiceStatusMutation(c.config, OpUpdateOne, withServiceStatusID(id))
	return &ServiceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for ServiceStatus.
func (c *ServiceStatusClient) Delete() *ServiceStatusDelete {
	mutation := newServiceStatusMutation(c.config, OpDelete)
	return &ServiceStatusDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ServiceStatusClient) DeleteOne(_m *ServiceStatus) *ServiceStatusDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ServiceStatusClient) DeleteOneID(id int) *ServiceStatusDeleteOne {
	builder := c.Delete().Where(servicestatus.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ServiceStatusDeleteOne{builder}
}

// Query returns a query builder for ServiceStatus.
func (c *ServiceStatusClient) Query() *ServiceStatusQuery {
	return &ServiceStatusQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeServiceStatus},
		inters: c.Interceptors(),
	}
}

// Get returns a ServiceStatus entity by its id.
func (c *ServiceStatusClient) Get(ctx context.Context, id int) (*ServiceStatus, error) {
	return c.Query().Where(servicestatus.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ServiceStatusClient) GetX(ctx context.Context, id int) *ServiceStatus {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *ServiceStatusClient) Hooks() []Hook {
	return c.hooks.ServiceStatus
}

// Interceptors returns the client interceptors.
func (c *ServiceStatusClient) Interceptors() []Interceptor {
	return c.inters.ServiceStatus
}

func (c *ServiceStatusClient) mutate(ctx context.Context, m *ServiceStatusMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ServiceStatusCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ServiceStatusUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ServiceStatusUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ServiceStatusDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown ServiceStatus mutation op: %q", m.Op())
	}
}

// TempFileClient is a client for the TempFile schema.
type TempFileClient struct {
	config
}

// NewTempFileClient returns a client for the TempFile from the given config.
func NewTempFileClient(c config) *TempFileClient {
	return &TempFileClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tempfile.Hooks(f(g(h())))`.
func (c *TempFileClient) Use(hooks ...Hook) {
	c.hooks.TempFile = append(c.hooks.TempFile, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tempfile.Intercept(f(g(h())))`.
func (c *TempFileClient) Intercept(interceptors ...Interceptor) {
	c.inters.TempFile = append(c.inters.TempFile, interceptors...)
}

// Create returns a builder for creating a TempFile entity.
func (c *TempFileClient) Create() *TempFileCreate {
	mutation := newTempFileMutation(c.config, OpCreate)
	return &TempFileCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TempFile entities.
func (c *TempFileClient) CreateBulk(builders ...*TempFileCreate) *TempFileCreateBulk {
	return &TempFileCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TempFileClient) MapCreateBulk(slice any, setFunc func(*TempFileCreate, int)) *TempFileCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TempFileCreateBulk{err: fmt.Errorf("calling to TempFileClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TempFileCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TempFileCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TempFile.
func (c *TempFileClient) Update() *TempFileUpdate {
	mutation := newTempFileMutation(c.config, OpUpdate)
	return &TempFileUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TempFileClient) UpdateOne(_m *TempFile) *TempFileUpdateOne {
	mutation := newTempFileMutation(c.config, OpUpdateOne, withTempFile(_m))
	return &TempFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TempFileClient) UpdateOneID(id int) *TempFileUpdateOne {
	mutation := newTempFileMutation(c.config, OpUpdateOne, withTempFileID(id))
	return &TempFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TempFile.
func (c *TempFileClient) Delete() *TempFileDelete {
	mutation := newTempFileMutation(c.config, OpDelete)
	return &TempFileDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TempFileClient) DeleteOne(_m *TempFile) *TempFileDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TempFileClient) DeleteOneID(id int) *TempFileDeleteOne {
	builder := c.Delete().Where(tempfile.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TempFileDeleteOne{builder}
}

// Query returns a query builder for TempFile.
func (c *TempFileClient) Query() *TempFileQuery {
	return &TempFileQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTempFile},
		inters: c.Interceptors(),
	}
}

// Get returns a TempFile entity by its id.
func (c *TempFileClient) Get(ctx context.Context, id int) (*TempFile, error) {
	return c.Query().Where(tempfile.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TempFileClient) GetX(ctx context.Context, id int) *TempFile {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TempFileClient) Hooks() []Hook {
	return c.hooks.TempFile
}

// Interceptors returns the client interceptors.
func (c *TempFileClient) Interceptors() []Interceptor {
	return c.inters.TempFile
}

func (c *TempFileClient) mutate(ctx context.Context, m *TempFileMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TempFileCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TempFileUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TempFileUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TempFileDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TempFile mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(_m *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(_m))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(_m *User) *UserDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		File, FileInfo, FileLink, FilePath, FileRole, ServiceStatus, TempFile,
		User []ent.Hook
	}
	inters struct {
		File, FileInfo, FileLink, FilePath, FileRole, ServiceStatus, TempFile,
		User []ent.Interceptor
	}
)
