// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starfrag-lab/retrowin-go/ent/filedata"
	"github.com/starfrag-lab/retrowin-go/ent/inode"
)

// FileDataCreate is the builder for creating a FileData entity.
type FileDataCreate struct {
	config
	mutation *FileDataMutation
	hooks    []Hook
}

// SetInodeID sets the "inode_id" field.
func (_c *FileDataCreate) SetInodeID(v int64) *FileDataCreate {
	_c.mutation.SetInodeID(v)
	return _c
}

// SetStorageType sets the "storage_type" field.
func (_c *FileDataCreate) SetStorageType(v filedata.StorageType) *FileDataCreate {
	_c.mutation.SetStorageType(v)
	return _c
}

// SetNillableStorageType sets the "storage_type" field if the given value is not nil.
func (_c *FileDataCreate) SetNillableStorageType(v *filedata.StorageType) *FileDataCreate {
	if v != nil {
		_c.SetStorageType(*v)
	}
	return _c
}

// SetLocation sets the "location" field.
func (_c *FileDataCreate) SetLocation(v string) *FileDataCreate {
	_c.mutation.SetLocation(v)
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *FileDataCreate) SetChecksum(v string) *FileDataCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetNillableChecksum sets the "checksum" field if the given value is not nil.
func (_c *FileDataCreate) SetNillableChecksum(v *string) *FileDataCreate {
	if v != nil {
		_c.SetChecksum(*v)
	}
	return _c
}

// SetInode sets the "inode" edge to the Inode entity.
func (_c *FileDataCreate) SetInode(v *Inode) *FileDataCreate {
	return _c.SetInodeID(v.ID)
}

// Mutation returns the FileDataMutation object of the builder.
func (_c *FileDataCreate) Mutation() *FileDataMutation {
	return _c.mutation
}

// Save creates the FileData in the database.
func (_c *FileDataCreate) Save(ctx context.Context) (*FileData, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileDataCreate) SaveX(ctx context.Context) *FileData {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileDataCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileDataCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileDataCreate) defaults() {
	if _, ok := _c.mutation.StorageType(); !ok {
		v := filedata.DefaultStorageType
		_c.mutation.SetStorageType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileDataCreate) check() error {
	if _, ok := _c.mutation.InodeID(); !ok {
		return &ValidationError{Name: "inode_id", err: errors.New(`ent: missing required field "FileData.inode_id"`)}
	}
	if _, ok := _c.mutation.StorageType(); !ok {
		return &ValidationError{Name: "storage_type", err: errors.New(`ent: missing required field "FileData.storage_type"`)}
	}
	if v, ok := _c.mutation.StorageType(); ok {
		if err := filedata.StorageTypeValidator(v); err != nil {
			return &ValidationError{Name: "storage_type", err: fmt.Errorf(`ent: validator failed for field "FileData.storage_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Location(); !ok {
		return &ValidationError{Name: "location", err: errors.New(`ent: missing required field "FileData.location"`)}
	}
	if v, ok := _c.mutation.Location(); ok {
		if err := filedata.LocationValidator(v); err != nil {
			return &ValidationError{Name: "location", err: fmt.Errorf(`ent: validator failed for field "FileData.location": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Checksum(); ok {
		if err := filedata.ChecksumValidator(v); err != nil {
			return &ValidationError{Name: "checksum", err: fmt.Errorf(`ent: validator failed for field "FileData.checksum": %w`, err)}
		}
	}
	if len(_c.mutation.InodeIDs()) == 0 {
		return &ValidationError{Name: "inode", err: errors.New(`ent: missing required edge "FileData.inode"`)}
	}
	return nil
}

func (_c *FileDataCreate) sqlSave(ctx context.Context) (*FileData, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileDataCreate) createSpec() (*FileData, *sqlgraph.CreateSpec) {
	var (
		_node = &FileData{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(filedata.Table, sqlgraph.NewFieldSpec(filedata.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.StorageType(); ok {
		_spec.SetField(filedata.FieldStorageType, field.TypeEnum, value)
		_node.StorageType = value
	}
	if value, ok := _c.mutation.Location(); ok {
		_spec.SetField(filedata.FieldLocation, field.TypeString, value)
		_node.Location = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(filedata.FieldChecksum, field.TypeString, value)
		_node.Checksum = &value
	}
	if nodes := _c.mutation.InodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filedata.InodeTable,
			Columns: []string{filedata.InodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileDataCreateBulk is the builder for creating many FileData entities in bulk.
type FileDataCreateBulk struct {
	config
	err      error
	builders []*FileDataCreate
}

// Save creates the FileData entities in the database.
func (_c *FileDataCreateBulk) Save(ctx context.Context) ([]*FileData, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileData, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileDataMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileDataCreateBulk) SaveX(ctx context.Context) []*FileData {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileDataCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileDataCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
