// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starfrag-lab/retrowin-go/ent/inode"
	"github.com/starfrag-lab/retrowin-go/ent/system"
)

// InodeCreate is the builder for creating a Inode entity.
type InodeCreate struct {
	config
	mutation *InodeMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *InodeCreate) SetCreateTime(v time.Time) *InodeCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *InodeCreate) SetNillableCreateTime(v *time.Time) *InodeCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *InodeCreate) SetUpdateTime(v time.Time) *InodeCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *InodeCreate) SetNillableUpdateTime(v *time.Time) *InodeCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetSystemID sets the "system_id" field.
func (_c *InodeCreate) SetSystemID(v string) *InodeCreate {
	_c.mutation.SetSystemID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *InodeCreate) SetMode(v int16) *InodeCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetUID sets the "uid" field.
func (_c *InodeCreate) SetUID(v int64) *InodeCreate {
	_c.mutation.SetUID(v)
	return _c
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (_c *InodeCreate) SetNillableUID(v *int64) *InodeCreate {
	if v != nil {
		_c.SetUID(*v)
	}
	return _c
}

// SetGid sets the "gid" field.
func (_c *InodeCreate) SetGid(v int64) *InodeCreate {
	_c.mutation.SetGid(v)
	return _c
}

// SetNillableGid sets the "gid" field if the given value is not nil.
func (_c *InodeCreate) SetNillableGid(v *int64) *InodeCreate {
	if v != nil {
		_c.SetGid(*v)
	}
	return _c
}

// SetSize sets the "size" field.
func (_c *InodeCreate) SetSize(v int64) *InodeCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_c *InodeCreate) SetNillableSize(v *int64) *InodeCreate {
	if v != nil {
		_c.SetSize(*v)
	}
	return _c
}

// SetLinkCount sets the "link_count" field.
func (_c *InodeCreate) SetLinkCount(v int) *InodeCreate {
	_c.mutation.SetLinkCount(v)
	return _c
}

// SetNillableLinkCount sets the "link_count" field if the given value is not nil.
func (_c *InodeCreate) SetNillableLinkCount(v *int) *InodeCreate {
	if v != nil {
		_c.SetLinkCount(*v)
	}
	return _c
}

// SetFlags sets the "flags" field.
func (_c *InodeCreate) SetFlags(v int16) *InodeCreate {
	_c.mutation.SetFlags(v)
	return _c
}

// SetAtime sets the "atime" field.
func (_c *InodeCreate) SetAtime(v time.Time) *InodeCreate {
	_c.mutation.SetAtime(v)
	return _c
}

// SetMtime sets the "mtime" field.
func (_c *InodeCreate) SetMtime(v time.Time) *InodeCreate {
	_c.mutation.SetMtime(v)
	return _c
}

// SetCtime sets the "ctime" field.
func (_c *InodeCreate) SetCtime(v time.Time) *InodeCreate {
	_c.mutation.SetCtime(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *InodeCreate) SetContent(v []byte) *InodeCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetID sets the "id" field.
func (_c *InodeCreate) SetID(v int64) *InodeCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSystem sets the "system" edge to the System entity.
func (_c *InodeCreate) SetSystem(v *System) *InodeCreate {
	return _c.SetSystemID(v.ID)
}

// Mutation returns the InodeMutation object of the builder.
func (_c *InodeCreate) Mutation() *InodeMutation {
	return _c.mutation
}

// Save creates the Inode in the database.
func (_c *InodeCreate) Save(ctx context.Context) (*Inode, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InodeCreate) SaveX(ctx context.Context) *Inode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InodeCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := inode.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := inode.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.UID(); !ok {
		v := inode.DefaultUID
		_c.mutation.SetUID(v)
	}
	if _, ok := _c.mutation.Gid(); !ok {
		v := inode.DefaultGid
		_c.mutation.SetGid(v)
	}
	if _, ok := _c.mutation.Size(); !ok {
		v := inode.DefaultSize
		_c.mutation.SetSize(v)
	}
	if _, ok := _c.mutation.LinkCount(); !ok {
		v := inode.DefaultLinkCount
		_c.mutation.SetLinkCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InodeCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Inode.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Inode.update_time"`)}
	}
	if _, ok := _c.mutation.SystemID(); !ok {
		return &ValidationError{Name: "system_id", err: errors.New(`ent: missing required field "Inode.system_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "Inode.mode"`)}
	}
	if _, ok := _c.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Inode.uid"`)}
	}
	if _, ok := _c.mutation.Gid(); !ok {
		return &ValidationError{Name: "gid", err: errors.New(`ent: missing required field "Inode.gid"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Inode.size"`)}
	}
	if _, ok := _c.mutation.LinkCount(); !ok {
		return &ValidationError{Name: "link_count", err: errors.New(`ent: missing required field "Inode.link_count"`)}
	}
	if _, ok := _c.mutation.Flags(); !ok {
		return &ValidationError{Name: "flags", err: errors.New(`ent: missing required field "Inode.flags"`)}
	}
	if _, ok := _c.mutation.Atime(); !ok {
		return &ValidationError{Name: "atime", err: errors.New(`ent: missing required field "Inode.atime"`)}
	}
	if _, ok := _c.mutation.Mtime(); !ok {
		return &ValidationError{Name: "mtime", err: errors.New(`ent: missing required field "Inode.mtime"`)}
	}
	if _, ok := _c.mutation.Ctime(); !ok {
		return &ValidationError{Name: "ctime", err: errors.New(`ent: missing required field "Inode.ctime"`)}
	}
	if len(_c.mutation.SystemIDs()) == 0 {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required edge "Inode.system"`)}
	}
	return nil
}

func (_c *InodeCreate) sqlSave(ctx context.Context) (*Inode, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InodeCreate) createSpec() (*Inode, *sqlgraph.CreateSpec) {
	var (
		_node = &Inode{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inode.Table, sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(inode.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(inode.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(inode.FieldMode, field.TypeInt16, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.UID(); ok {
		_spec.SetField(inode.FieldUID, field.TypeInt64, value)
		_node.UID = value
	}
	if value, ok := _c.mutation.Gid(); ok {
		_spec.SetField(inode.FieldGid, field.TypeInt64, value)
		_node.Gid = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(inode.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.LinkCount(); ok {
		_spec.SetField(inode.FieldLinkCount, field.TypeInt, value)
		_node.LinkCount = value
	}
	if value, ok := _c.mutation.Flags(); ok {
		_spec.SetField(inode.FieldFlags, field.TypeInt16, value)
		_node.Flags = value
	}
	if value, ok := _c.mutation.Atime(); ok {
		_spec.SetField(inode.FieldAtime, field.TypeTime, value)
		_node.Atime = value
	}
	if value, ok := _c.mutation.Mtime(); ok {
		_spec.SetField(inode.FieldMtime, field.TypeTime, value)
		_node.Mtime = value
	}
	if value, ok := _c.mutation.Ctime(); ok {
		_spec.SetField(inode.FieldCtime, field.TypeTime, value)
		_node.Ctime = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(inode.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if nodes := _c.mutation.SystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inode.SystemTable,
			Columns: []string{inode.SystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(system.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SystemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InodeCreateBulk is the builder for creating many Inode entities in bulk.
type InodeCreateBulk struct {
	config
	err      error
	builders []*InodeCreate
}

// Save creates the Inode entities in the database.
func (_c *InodeCreateBulk) Save(ctx context.Context) ([]*Inode, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Inode, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InodeCreateBulk) SaveX(ctx context.Context) []*Inode {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
