// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starfrag-lab/retrowin-go/ent/object"
	"github.com/starfrag-lab/retrowin-go/ent/system"
)

// ObjectCreate is the builder for creating a Object entity.
type ObjectCreate struct {
	config
	mutation *ObjectMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *ObjectCreate) SetCreateTime(v time.Time) *ObjectCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableCreateTime(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ObjectCreate) SetUpdateTime(v time.Time) *ObjectCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableUpdateTime(v *time.Time) *ObjectCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *ObjectCreate) SetProvider(v object.Provider) *ObjectCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *ObjectCreate) SetNillableProvider(v *object.Provider) *ObjectCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetBucket sets the "bucket" field.
func (_c *ObjectCreate) SetBucket(v string) *ObjectCreate {
	_c.mutation.SetBucket(v)
	return _c
}

// SetSystemID sets the "system_id" field.
func (_c *ObjectCreate) SetSystemID(v string) *ObjectCreate {
	_c.mutation.SetSystemID(v)
	return _c
}

// SetStorageKey sets the "storage_key" field.
func (_c *ObjectCreate) SetStorageKey(v string) *ObjectCreate {
	_c.mutation.SetStorageKey(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ObjectCreate) SetID(v string) *ObjectCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSystem sets the "system" edge to the System entity.
func (_c *ObjectCreate) SetSystem(v *System) *ObjectCreate {
	return _c.SetSystemID(v.ID)
}

// Mutation returns the ObjectMutation object of the builder.
func (_c *ObjectCreate) Mutation() *ObjectMutation {
	return _c.mutation
}

// Save creates the Object in the database.
func (_c *ObjectCreate) Save(ctx context.Context) (*Object, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ObjectCreate) SaveX(ctx context.Context) *Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ObjectCreate) defaults() {
	if _, ok := _c.mutation.CreateTime(); !ok {
		v := object.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		v := object.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.Provider(); !ok {
		v := object.DefaultProvider
		_c.mutation.SetProvider(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ObjectCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "Object.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "Object.update_time"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "Object.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := object.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "Object.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Bucket(); !ok {
		return &ValidationError{Name: "bucket", err: errors.New(`ent: missing required field "Object.bucket"`)}
	}
	if _, ok := _c.mutation.SystemID(); !ok {
		return &ValidationError{Name: "system_id", err: errors.New(`ent: missing required field "Object.system_id"`)}
	}
	if _, ok := _c.mutation.StorageKey(); !ok {
		return &ValidationError{Name: "storage_key", err: errors.New(`ent: missing required field "Object.storage_key"`)}
	}
	if len(_c.mutation.SystemIDs()) == 0 {
		return &ValidationError{Name: "system", err: errors.New(`ent: missing required edge "Object.system"`)}
	}
	return nil
}

func (_c *ObjectCreate) sqlSave(ctx context.Context) (*Object, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Object.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ObjectCreate) createSpec() (*Object, *sqlgraph.CreateSpec) {
	var (
		_node = &Object{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(object.Table, sqlgraph.NewFieldSpec(object.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(object.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(object.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(object.FieldProvider, field.TypeEnum, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Bucket(); ok {
		_spec.SetField(object.FieldBucket, field.TypeString, value)
		_node.Bucket = value
	}
	if value, ok := _c.mutation.StorageKey(); ok {
		_spec.SetField(object.FieldStorageKey, field.TypeString, value)
		_node.StorageKey = value
	}
	if nodes := _c.mutation.SystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   object.SystemTable,
			Columns: []string{object.SystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(system.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SystemID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ObjectCreateBulk is the builder for creating many Object entities in bulk.
type ObjectCreateBulk struct {
	config
	err      error
	builders []*ObjectCreate
}

// Save creates the Object entities in the database.
func (_c *ObjectCreateBulk) Save(ctx context.Context) ([]*Object, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Object, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ObjectMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ObjectCreateBulk) SaveX(ctx context.Context) []*Object {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ObjectCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ObjectCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
