// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/starfrag-lab/retrowin-go/ent/file"
	"github.com/starfrag-lab/retrowin-go/ent/fileinfo"
	"github.com/starfrag-lab/retrowin-go/ent/filelink"
	"github.com/starfrag-lab/retrowin-go/ent/filerole"
	"github.com/starfrag-lab/retrowin-go/ent/schema"
	"github.com/starfrag-lab/retrowin-go/ent/servicestatus"
	"github.com/starfrag-lab/retrowin-go/ent/tempfile"
	"github.com/starfrag-lab/retrowin-go/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileMixin := schema.File{}.Mixin()
	fileMixinFields0 := fileMixin[0].Fields()
	_ = fileMixinFields0
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescCreateTime is the schema descriptor for create_time field.
	fileDescCreateTime := fileMixinFields0[0].Descriptor()
	// file.DefaultCreateTime holds the default value on creation for the create_time field.
	file.DefaultCreateTime = fileDescCreateTime.Default.(func() time.Time)
	// fileDescUpdateTime is the schema descriptor for update_time field.
	fileDescUpdateTime := fileMixinFields0[1].Descriptor()
	// file.DefaultUpdateTime holds the default value on creation for the update_time field.
	file.DefaultUpdateTime = fileDescUpdateTime.Default.(func() time.Time)
	// file.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	file.UpdateDefaultUpdateTime = fileDescUpdateTime.UpdateDefault.(func() time.Time)
	// fileDescFileName is the schema descriptor for file_name field.
	fileDescFileName := fileFields[2].Descriptor()
	// file.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	file.FileNameValidator = fileDescFileName.Validators[0].(func(string) error)
	// fileDescByteSize is the schema descriptor for byte_size field.
	fileDescByteSize := fileFields[5].Descriptor()
	// file.DefaultByteSize holds the default value on creation for the byte_size field.
	file.DefaultByteSize = fileDescByteSize.Default.(int64)
	// fileDescIsSystem is the schema descriptor for is_system field.
	fileDescIsSystem := fileFields[6].Descriptor()
	// file.DefaultIsSystem holds the default value on creation for the is_system field.
	file.DefaultIsSystem = fileDescIsSystem.Default.(bool)
	// fileDescSystemType is the schema descriptor for system_type field.
	fileDescSystemType := fileFields[7].Descriptor()
	// file.SystemTypeValidator is a validator for the "system_type" field. It is called by the builders before save.
	file.SystemTypeValidator = fileDescSystemType.Validators[0].(func(string) error)
	fileinfoFields := schema.FileInfo{}.Fields()
	_ = fileinfoFields
	// fileinfoDescCreateDate is the schema descriptor for create_date field.
	fileinfoDescCreateDate := fileinfoFields[1].Descriptor()
	// fileinfo.DefaultCreateDate holds the default value on creation for the create_date field.
	fileinfo.DefaultCreateDate = fileinfoDescCreateDate.Default.(func() time.Time)
	// fileinfoDescUpdateDate is the schema descriptor for update_date field.
	fileinfoDescUpdateDate := fileinfoFields[2].Descriptor()
	// fileinfo.DefaultUpdateDate holds the default value on creation for the update_date field.
	fileinfo.DefaultUpdateDate = fileinfoDescUpdateDate.Default.(func() time.Time)
	// fileinfo.UpdateDefaultUpdateDate holds the default value on update for the update_date field.
	fileinfo.UpdateDefaultUpdateDate = fileinfoDescUpdateDate.UpdateDefault.(func() time.Time)
	// fileinfoDescByteSize is the schema descriptor for byte_size field.
	fileinfoDescByteSize := fileinfoFields[3].Descriptor()
	// fileinfo.DefaultByteSize holds the default value on creation for the byte_size field.
	fileinfo.DefaultByteSize = fileinfoDescByteSize.Default.(int64)
	filelinkMixin := schema.FileLink{}.Mixin()
	filelinkMixinFields0 := filelinkMixin[0].Fields()
	_ = filelinkMixinFields0
	filelinkFields := schema.FileLink{}.Fields()
	_ = filelinkFields
	// filelinkDescCreateTime is the schema descriptor for create_time field.
	filelinkDescCreateTime := filelinkMixinFields0[0].Descriptor()
	// filelink.DefaultCreateTime holds the default value on creation for the create_time field.
	filelink.DefaultCreateTime = filelinkDescCreateTime.Default.(func() time.Time)
	// filelinkDescUpdateTime is the schema descriptor for update_time field.
	filelinkDescUpdateTime := filelinkMixinFields0[1].Descriptor()
	// filelink.DefaultUpdateTime holds the default value on creation for the update_time field.
	filelink.DefaultUpdateTime = filelinkDescUpdateTime.Default.(func() time.Time)
	// filelink.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	filelink.UpdateDefaultUpdateTime = filelinkDescUpdateTime.UpdateDefault.(func() time.Time)
	fileroleMixin := schema.FileRole{}.Mixin()
	fileroleMixinFields0 := fileroleMixin[0].Fields()
	_ = fileroleMixinFields0
	fileroleFields := schema.FileRole{}.Fields()
	_ = fileroleFields
	// fileroleDescCreateTime is the schema descriptor for create_time field.
	fileroleDescCreateTime := fileroleMixinFields0[0].Descriptor()
	// filerole.DefaultCreateTime holds the default value on creation for the create_time field.
	filerole.DefaultCreateTime = fileroleDescCreateTime.Default.(func() time.Time)
	// fileroleDescUpdateTime is the schema descriptor for update_time field.
	fileroleDescUpdateTime := fileroleMixinFields0[1].Descriptor()
	// filerole.DefaultUpdateTime holds the default value on creation for the update_time field.
	filerole.DefaultUpdateTime = fileroleDescUpdateTime.Default.(func() time.Time)
	// filerole.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	filerole.UpdateDefaultUpdateTime = fileroleDescUpdateTime.UpdateDefault.(func() time.Time)
	// fileroleDescRoles is the schema descriptor for roles field.
	fileroleDescRoles := fileroleFields[2].Descriptor()
	// filerole.DefaultRoles holds the default value on creation for the roles field.
	filerole.DefaultRoles = fileroleDescRoles.Default.([]string)
	servicestatusFields := schema.ServiceStatus{}.Fields()
	_ = servicestatusFields
	// servicestatusDescAvailable is the schema descriptor for available field.
	servicestatusDescAvailable := servicestatusFields[1].Descriptor()
	// servicestatus.DefaultAvailable holds the default value on creation for the available field.
	servicestatus.DefaultAvailable = servicestatusDescAvailable.Default.(bool)
	// servicestatusDescJoinDate is the schema descriptor for join_date field.
	servicestatusDescJoinDate := servicestatusFields[2].Descriptor()
	// servicestatus.DefaultJoinDate holds the default value on creation for the join_date field.
	servicestatus.DefaultJoinDate = servicestatusDescJoinDate.Default.(func() time.Time)
	// servicestatusDescUpdateDate is the schema descriptor for update_date field.
	servicestatusDescUpdateDate := servicestatusFields[3].Descriptor()
	// servicestatus.DefaultUpdateDate holds the default value on creation for the update_date field.
	servicestatus.DefaultUpdateDate = servicestatusDescUpdateDate.Default.(func() time.Time)
	// servicestatus.UpdateDefaultUpdateDate holds the default value on update for the update_date field.
	servicestatus.UpdateDefaultUpdateDate = servicestatusDescUpdateDate.UpdateDefault.(func() time.Time)
	tempfileFields := schema.TempFile{}.Fields()
	_ = tempfileFields
	// tempfileDescFileName is the schema descriptor for file_name field.
	tempfileDescFileName := tempfileFields[2].Descriptor()
	// tempfile.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	tempfile.FileNameValidator = tempfileDescFileName.Validators[0].(func(string) error)
	// tempfileDescByteSize is the schema descriptor for byte_size field.
	tempfileDescByteSize := tempfileFields[3].Descriptor()
	// tempfile.DefaultByteSize holds the default value on creation for the byte_size field.
	tempfile.DefaultByteSize = tempfileDescByteSize.Default.(int64)
	// tempfileDescCreateDate is the schema descriptor for create_date field.
	tempfileDescCreateDate := tempfileFields[4].Descriptor()
	// tempfile.DefaultCreateDate holds the default value on creation for the create_date field.
	tempfile.DefaultCreateDate = tempfileDescCreateDate.Default.(func() time.Time)
	// tempfileDescExpiresAt is the schema descriptor for expires_at field.
	tempfileDescExpiresAt := tempfileFields[6].Descriptor()
	// tempfile.DefaultExpiresAt holds the default value on creation for the expires_at field.
	tempfile.DefaultExpiresAt = tempfileDescExpiresAt.Default.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userMixinFields0[0].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
}
