// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starfrag-lab/retrowin-go/ent/inode"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
	"github.com/starfrag-lab/retrowin-go/ent/symlink"
)

// SymlinkUpdate is the builder for updating Symlink entities.
type SymlinkUpdate struct {
	config
	hooks    []Hook
	mutation *SymlinkMutation
}

// Where appends a list predicates to the SymlinkUpdate builder.
func (_u *SymlinkUpdate) Where(ps ...predicate.Symlink) *SymlinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInodeID sets the "inode_id" field.
func (_u *SymlinkUpdate) SetInodeID(v int64) *SymlinkUpdate {
	_u.mutation.SetInodeID(v)
	return _u
}

// SetNillableInodeID sets the "inode_id" field if the given value is not nil.
func (_u *SymlinkUpdate) SetNillableInodeID(v *int64) *SymlinkUpdate {
	if v != nil {
		_u.SetInodeID(*v)
	}
	return _u
}

// SetTargetPath sets the "target_path" field.
func (_u *SymlinkUpdate) SetTargetPath(v string) *SymlinkUpdate {
	_u.mutation.SetTargetPath(v)
	return _u
}

// SetNillableTargetPath sets the "target_path" field if the given value is not nil.
func (_u *SymlinkUpdate) SetNillableTargetPath(v *string) *SymlinkUpdate {
	if v != nil {
		_u.SetTargetPath(*v)
	}
	return _u
}

// SetInode sets the "inode" edge to the Inode entity.
func (_u *SymlinkUpdate) SetInode(v *Inode) *SymlinkUpdate {
	return _u.SetInodeID(v.ID)
}

// Mutation returns the SymlinkMutation object of the builder.
func (_u *SymlinkUpdate) Mutation() *SymlinkMutation {
	return _u.mutation
}

// ClearInode clears the "inode" edge to the Inode entity.
func (_u *SymlinkUpdate) ClearInode() *SymlinkUpdate {
	_u.mutation.ClearInode()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SymlinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SymlinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SymlinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SymlinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SymlinkUpdate) check() error {
	if v, ok := _u.mutation.TargetPath(); ok {
		if err := symlink.TargetPathValidator(v); err != nil {
			return &ValidationError{Name: "target_path", err: fmt.Errorf(`ent: validator failed for field "Symlink.target_path": %w`, err)}
		}
	}
	if _u.mutation.InodeCleared() && len(_u.mutation.InodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Symlink.inode"`)
	}
	return nil
}

func (_u *SymlinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(symlink.Table, symlink.Columns, sqlgraph.NewFieldSpec(symlink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetPath(); ok {
		_spec.SetField(symlink.FieldTargetPath, field.TypeString, value)
	}
	if _u.mutation.InodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   symlink.InodeTable,
			Columns: []string{symlink.InodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   symlink.InodeTable,
			Columns: []string{symlink.InodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{symlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SymlinkUpdateOne is the builder for updating a single Symlink entity.
type SymlinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SymlinkMutation
}

// SetInodeID sets the "inode_id" field.
func (_u *SymlinkUpdateOne) SetInodeID(v int64) *SymlinkUpdateOne {
	_u.mutation.SetInodeID(v)
	return _u
}

// SetNillableInodeID sets the "inode_id" field if the given value is not nil.
func (_u *SymlinkUpdateOne) SetNillableInodeID(v *int64) *SymlinkUpdateOne {
	if v != nil {
		_u.SetInodeID(*v)
	}
	return _u
}

// SetTargetPath sets the "target_path" field.
func (_u *SymlinkUpdateOne) SetTargetPath(v string) *SymlinkUpdateOne {
	_u.mutation.SetTargetPath(v)
	return _u
}

// SetNillableTargetPath sets the "target_path" field if the given value is not nil.
func (_u *SymlinkUpdateOne) SetNillableTargetPath(v *string) *SymlinkUpdateOne {
	if v != nil {
		_u.SetTargetPath(*v)
	}
	return _u
}

// SetInode sets the "inode" edge to the Inode entity.
func (_u *SymlinkUpdateOne) SetInode(v *Inode) *SymlinkUpdateOne {
	return _u.SetInodeID(v.ID)
}

// Mutation returns the SymlinkMutation object of the builder.
func (_u *SymlinkUpdateOne) Mutation() *SymlinkMutation {
	return _u.mutation
}

// ClearInode clears the "inode" edge to the Inode entity.
func (_u *SymlinkUpdateOne) ClearInode() *SymlinkUpdateOne {
	_u.mutation.ClearInode()
	return _u
}

// Where appends a list predicates to the SymlinkUpdate builder.
func (_u *SymlinkUpdateOne) Where(ps ...predicate.Symlink) *SymlinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SymlinkUpdateOne) Select(field string, fields ...string) *SymlinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Symlink entity.
func (_u *SymlinkUpdateOne) Save(ctx context.Context) (*Symlink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SymlinkUpdateOne) SaveX(ctx context.Context) *Symlink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SymlinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SymlinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SymlinkUpdateOne) check() error {
	if v, ok := _u.mutation.TargetPath(); ok {
		if err := symlink.TargetPathValidator(v); err != nil {
			return &ValidationError{Name: "target_path", err: fmt.Errorf(`ent: validator failed for field "Symlink.target_path": %w`, err)}
		}
	}
	if _u.mutation.InodeCleared() && len(_u.mutation.InodeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Symlink.inode"`)
	}
	return nil
}

func (_u *SymlinkUpdateOne) sqlSave(ctx context.Context) (_node *Symlink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(symlink.Table, symlink.Columns, sqlgraph.NewFieldSpec(symlink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Symlink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, symlink.FieldID)
		for _, f := range fields {
			if !symlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != symlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetPath(); ok {
		_spec.SetField(symlink.FieldTargetPath, field.TypeString, value)
	}
	if _u.mutation.InodeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   symlink.InodeTable,
			Columns: []string{symlink.InodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   symlink.InodeTable,
			Columns: []string{symlink.InodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Symlink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{symlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
