// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
	"github.com/starfrag-lab/retrowin-go/ent/systemgroup"
	"github.com/starfrag-lab/retrowin-go/ent/usergroup"
	"github.com/starfrag-lab/retrowin-go/ent/usersystem"
)

// UserGroupUpdate is the builder for updating UserGroup entities.
type UserGroupUpdate struct {
	config
	hooks    []Hook
	mutation *UserGroupMutation
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (_u *UserGroupUpdate) Where(ps ...predicate.UserGroup) *UserGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserSystemID sets the "user_system_id" field.
func (_u *UserGroupUpdate) SetUserSystemID(v int) *UserGroupUpdate {
	_u.mutation.SetUserSystemID(v)
	return _u
}

// SetNillableUserSystemID sets the "user_system_id" field if the given value is not nil.
func (_u *UserGroupUpdate) SetNillableUserSystemID(v *int) *UserGroupUpdate {
	if v != nil {
		_u.SetUserSystemID(*v)
	}
	return _u
}

// SetSystemGroupID sets the "system_group_id" field.
func (_u *UserGroupUpdate) SetSystemGroupID(v int) *UserGroupUpdate {
	_u.mutation.SetSystemGroupID(v)
	return _u
}

// SetNillableSystemGroupID sets the "system_group_id" field if the given value is not nil.
func (_u *UserGroupUpdate) SetNillableSystemGroupID(v *int) *UserGroupUpdate {
	if v != nil {
		_u.SetSystemGroupID(*v)
	}
	return _u
}

// SetUserSystem sets the "user_system" edge to the UserSystem entity.
func (_u *UserGroupUpdate) SetUserSystem(v *UserSystem) *UserGroupUpdate {
	return _u.SetUserSystemID(v.ID)
}

// SetSystemGroup sets the "system_group" edge to the SystemGroup entity.
func (_u *UserGroupUpdate) SetSystemGroup(v *SystemGroup) *UserGroupUpdate {
	return _u.SetSystemGroupID(v.ID)
}

// Mutation returns the UserGroupMutation object of the builder.
func (_u *UserGroupUpdate) Mutation() *UserGroupMutation {
	return _u.mutation
}

// ClearUserSystem clears the "user_system" edge to the UserSystem entity.
func (_u *UserGroupUpdate) ClearUserSystem() *UserGroupUpdate {
	_u.mutation.ClearUserSystem()
	return _u
}

// ClearSystemGroup clears the "system_group" edge to the SystemGroup entity.
func (_u *UserGroupUpdate) ClearSystemGroup() *UserGroupUpdate {
	_u.mutation.ClearSystemGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupUpdate) check() error {
	if _u.mutation.UserSystemCleared() && len(_u.mutation.UserSystemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroup.user_system"`)
	}
	if _u.mutation.SystemGroupCleared() && len(_u.mutation.SystemGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroup.system_group"`)
	}
	return nil
}

func (_u *UserGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserSystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.UserSystemTable,
			Columns: []string{usergroup.UserSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.UserSystemTable,
			Columns: []string{usergroup.UserSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SystemGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.SystemGroupTable,
			Columns: []string{usergroup.SystemGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SystemGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.SystemGroupTable,
			Columns: []string{usergroup.SystemGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserGroupUpdateOne is the builder for updating a single UserGroup entity.
type UserGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserGroupMutation
}

// SetUserSystemID sets the "user_system_id" field.
func (_u *UserGroupUpdateOne) SetUserSystemID(v int) *UserGroupUpdateOne {
	_u.mutation.SetUserSystemID(v)
	return _u
}

// SetNillableUserSystemID sets the "user_system_id" field if the given value is not nil.
func (_u *UserGroupUpdateOne) SetNillableUserSystemID(v *int) *UserGroupUpdateOne {
	if v != nil {
		_u.SetUserSystemID(*v)
	}
	return _u
}

// SetSystemGroupID sets the "system_group_id" field.
func (_u *UserGroupUpdateOne) SetSystemGroupID(v int) *UserGroupUpdateOne {
	_u.mutation.SetSystemGroupID(v)
	return _u
}

// SetNillableSystemGroupID sets the "system_group_id" field if the given value is not nil.
func (_u *UserGroupUpdateOne) SetNillableSystemGroupID(v *int) *UserGroupUpdateOne {
	if v != nil {
		_u.SetSystemGroupID(*v)
	}
	return _u
}

// SetUserSystem sets the "user_system" edge to the UserSystem entity.
func (_u *UserGroupUpdateOne) SetUserSystem(v *UserSystem) *UserGroupUpdateOne {
	return _u.SetUserSystemID(v.ID)
}

// SetSystemGroup sets the "system_group" edge to the SystemGroup entity.
func (_u *UserGroupUpdateOne) SetSystemGroup(v *SystemGroup) *UserGroupUpdateOne {
	return _u.SetSystemGroupID(v.ID)
}

// Mutation returns the UserGroupMutation object of the builder.
func (_u *UserGroupUpdateOne) Mutation() *UserGroupMutation {
	return _u.mutation
}

// ClearUserSystem clears the "user_system" edge to the UserSystem entity.
func (_u *UserGroupUpdateOne) ClearUserSystem() *UserGroupUpdateOne {
	_u.mutation.ClearUserSystem()
	return _u
}

// ClearSystemGroup clears the "system_group" edge to the SystemGroup entity.
func (_u *UserGroupUpdateOne) ClearSystemGroup() *UserGroupUpdateOne {
	_u.mutation.ClearSystemGroup()
	return _u
}

// Where appends a list predicates to the UserGroupUpdate builder.
func (_u *UserGroupUpdateOne) Where(ps ...predicate.UserGroup) *UserGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserGroupUpdateOne) Select(field string, fields ...string) *UserGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserGroup entity.
func (_u *UserGroupUpdateOne) Save(ctx context.Context) (*UserGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserGroupUpdateOne) SaveX(ctx context.Context) *UserGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserGroupUpdateOne) check() error {
	if _u.mutation.UserSystemCleared() && len(_u.mutation.UserSystemIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroup.user_system"`)
	}
	if _u.mutation.SystemGroupCleared() && len(_u.mutation.SystemGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserGroup.system_group"`)
	}
	return nil
}

func (_u *UserGroupUpdateOne) sqlSave(ctx context.Context) (_node *UserGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usergroup.Table, usergroup.Columns, sqlgraph.NewFieldSpec(usergroup.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usergroup.FieldID)
		for _, f := range fields {
			if !usergroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usergroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserSystemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.UserSystemTable,
			Columns: []string{usergroup.UserSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersystem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserSystemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.UserSystemTable,
			Columns: []string{usergroup.UserSystemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usersystem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SystemGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.SystemGroupTable,
			Columns: []string{usergroup.SystemGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemgroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SystemGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usergroup.SystemGroupTable,
			Columns: []string{usergroup.SystemGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(systemgroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usergroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
