{{- if .Values.migration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "retrowin.fullname" . }}-migration-{{ .Release.Revision }}
  labels:
    {{- include "retrowin.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        {{- include "retrowin.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "retrowin.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migration
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "retrowin.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - migrate
            - apply
            - --config
            - /app/config/config.yaml
          env:
            {{- if or .Values.secrets.database.password .Values.secrets.database.existingSecret }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.database.existingSecret | default (include "retrowin.fullname" .) }}
                  key: {{ .Values.secrets.database.existingSecretKey | default "database-password" }}
            {{- end }}
            {{- if or .Values.secrets.cache.valkey.password .Values.secrets.cache.valkey.existingSecret }}
            - name: CACHE_VALKEY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.cache.valkey.existingSecret | default (include "retrowin.fullname" .) }}
                  key: {{ .Values.secrets.cache.valkey.existingSecretKey | default "valkey-password" }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "retrowin.fullname" . }}
{{- end }}
