{{- if or .Values.secrets.database.password .Values.secrets.cache.valkey.password .Values.secrets.keycloak.clientSecret .Values.config.auth.gatewaySecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "retrowin.fullname" . }}
  labels:
    {{- include "retrowin.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-2"
type: Opaque
data:
  {{- if .Values.secrets.database.password }}
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.cache.valkey.password }}
  valkey-password: {{ .Values.secrets.cache.valkey.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.keycloak.clientSecret }}
  keycloak-client-secret: {{ .Values.secrets.keycloak.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.auth.gatewaySecret }}
  gateway-secret: {{ .Values.config.auth.gatewaySecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.storage.accessKey }}
  storage-access-key: {{ .Values.secrets.storage.accessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.storage.secretKey }}
  storage-secret-key: {{ .Values.secrets.storage.secretKey | b64enc | quote }}
  {{- end }}
{{- end }}
