// Code generated by ent, DO NOT EDIT.

package servicestatus

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldUserID, v))
}

// Available applies equality check predicate on the "available" field. It's identical to AvailableEQ.
func Available(v bool) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldAvailable, v))
}

// JoinDate applies equality check predicate on the "join_date" field. It's identical to JoinDateEQ.
func JoinDate(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldJoinDate, v))
}

// UpdateDate applies equality check predicate on the "update_date" field. It's identical to UpdateDateEQ.
func UpdateDate(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldUpdateDate, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLTE(FieldUserID, v))
}

// AvailableEQ applies the EQ predicate on the "available" field.
func AvailableEQ(v bool) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldAvailable, v))
}

// AvailableNEQ applies the NEQ predicate on the "available" field.
func AvailableNEQ(v bool) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNEQ(FieldAvailable, v))
}

// JoinDateEQ applies the EQ predicate on the "join_date" field.
func JoinDateEQ(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldJoinDate, v))
}

// JoinDateNEQ applies the NEQ predicate on the "join_date" field.
func JoinDateNEQ(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNEQ(FieldJoinDate, v))
}

// JoinDateIn applies the In predicate on the "join_date" field.
func JoinDateIn(vs ...time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldIn(FieldJoinDate, vs...))
}

// JoinDateNotIn applies the NotIn predicate on the "join_date" field.
func JoinDateNotIn(vs ...time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNotIn(FieldJoinDate, vs...))
}

// JoinDateGT applies the GT predicate on the "join_date" field.
func JoinDateGT(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGT(FieldJoinDate, v))
}

// JoinDateGTE applies the GTE predicate on the "join_date" field.
func JoinDateGTE(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGTE(FieldJoinDate, v))
}

// JoinDateLT applies the LT predicate on the "join_date" field.
func JoinDateLT(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLT(FieldJoinDate, v))
}

// JoinDateLTE applies the LTE predicate on the "join_date" field.
func JoinDateLTE(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLTE(FieldJoinDate, v))
}

// UpdateDateEQ applies the EQ predicate on the "update_date" field.
func UpdateDateEQ(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldEQ(FieldUpdateDate, v))
}

// UpdateDateNEQ applies the NEQ predicate on the "update_date" field.
func UpdateDateNEQ(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNEQ(FieldUpdateDate, v))
}

// UpdateDateIn applies the In predicate on the "update_date" field.
func UpdateDateIn(vs ...time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldIn(FieldUpdateDate, vs...))
}

// UpdateDateNotIn applies the NotIn predicate on the "update_date" field.
func UpdateDateNotIn(vs ...time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldNotIn(FieldUpdateDate, vs...))
}

// UpdateDateGT applies the GT predicate on the "update_date" field.
func UpdateDateGT(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGT(FieldUpdateDate, v))
}

// UpdateDateGTE applies the GTE predicate on the "update_date" field.
func UpdateDateGTE(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldGTE(FieldUpdateDate, v))
}

// UpdateDateLT applies the LT predicate on the "update_date" field.
func UpdateDateLT(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLT(FieldUpdateDate, v))
}

// UpdateDateLTE applies the LTE predicate on the "update_date" field.
func UpdateDateLTE(v time.Time) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.FieldLTE(FieldUpdateDate, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ServiceStatus) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ServiceStatus) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ServiceStatus) predicate.ServiceStatus {
	return predicate.ServiceStatus(sql.NotPredicates(p))
}
