// Code generated by ent, DO NOT EDIT.

package inode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the inode type in the database.
	Label = "inode"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldSystemID holds the string denoting the system_id field in the database.
	FieldSystemID = "system_id"
	// FieldMode holds the string denoting the mode field in the database.
	FieldMode = "mode"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldGid holds the string denoting the gid field in the database.
	FieldGid = "gid"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// FieldLinkCount holds the string denoting the link_count field in the database.
	FieldLinkCount = "link_count"
	// FieldFlags holds the string denoting the flags field in the database.
	FieldFlags = "flags"
	// FieldAtime holds the string denoting the atime field in the database.
	FieldAtime = "atime"
	// FieldMtime holds the string denoting the mtime field in the database.
	FieldMtime = "mtime"
	// FieldCtime holds the string denoting the ctime field in the database.
	FieldCtime = "ctime"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// EdgeSystem holds the string denoting the system edge name in mutations.
	EdgeSystem = "system"
	// Table holds the table name of the inode in the database.
	Table = "inodes"
	// SystemTable is the table that holds the system relation/edge.
	SystemTable = "inodes"
	// SystemInverseTable is the table name for the System entity.
	// It exists in this package in order to avoid circular dependency with the "system" package.
	SystemInverseTable = "systems"
	// SystemColumn is the table column denoting the system relation/edge.
	SystemColumn = "system_id"
)

// Columns holds all SQL columns for inode fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldSystemID,
	FieldMode,
	FieldUID,
	FieldGid,
	FieldSize,
	FieldLinkCount,
	FieldFlags,
	FieldAtime,
	FieldMtime,
	FieldCtime,
	FieldContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultUID holds the default value on creation for the "uid" field.
	DefaultUID int
	// DefaultGid holds the default value on creation for the "gid" field.
	DefaultGid int
	// DefaultSize holds the default value on creation for the "size" field.
	DefaultSize int64
	// DefaultLinkCount holds the default value on creation for the "link_count" field.
	DefaultLinkCount int
)

// OrderOption defines the ordering options for the Inode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// BySystemID orders the results by the system_id field.
func BySystemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemID, opts...).ToFunc()
}

// ByMode orders the results by the mode field.
func ByMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMode, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByGid orders the results by the gid field.
func ByGid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGid, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByLinkCount orders the results by the link_count field.
func ByLinkCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLinkCount, opts...).ToFunc()
}

// ByFlags orders the results by the flags field.
func ByFlags(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFlags, opts...).ToFunc()
}

// ByAtime orders the results by the atime field.
func ByAtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAtime, opts...).ToFunc()
}

// ByMtime orders the results by the mtime field.
func ByMtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMtime, opts...).ToFunc()
}

// ByCtime orders the results by the ctime field.
func ByCtime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCtime, opts...).ToFunc()
}

// BySystemField orders the results by system field.
func BySystemField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSystemStep(), sql.OrderByField(field, opts...))
	}
}
func newSystemStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SystemInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SystemTable, SystemColumn),
	)
}
