-- Create "ent_types" table for global unique ID allocation
CREATE TABLE "ent_types" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "type" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "ent_types_type_key" UNIQUE ("type")
);
-- Create "systems" table
CREATE TABLE "systems" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  PRIMARY KEY ("id")
);
-- Create index "system_name" to table: "systems"
CREATE INDEX "system_name" ON "systems" ("name");
-- Create index "system_status" to table: "systems"
CREATE INDEX "system_status" ON "systems" ("status");
-- Create "inodes" table
CREATE TABLE "inodes" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "mode" bigint NOT NULL,
  "uid" bigint NOT NULL DEFAULT 0,
  "gid" bigint NOT NULL DEFAULT 0,
  "size" bigint NOT NULL DEFAULT 0,
  "link_count" bigint NOT NULL DEFAULT 1,
  "flags" bigint NOT NULL,
  "atime" timestamptz NOT NULL,
  "mtime" timestamptz NOT NULL,
  "ctime" timestamptz NOT NULL,
  "content" bytea NULL,
  "system_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "inodes_systems_inodes" FOREIGN KEY ("system_id") REFERENCES "systems" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "inode_system_id" to table: "inodes"
CREATE INDEX "inode_system_id" ON "inodes" ("system_id");
-- Create "objects" table
CREATE TABLE "objects" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "provider" character varying NOT NULL DEFAULT 's3',
  "bucket" character varying NOT NULL,
  "storage_key" character varying NOT NULL,
  "status" character varying NOT NULL DEFAULT 'active',
  "system_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "objects_systems_objects" FOREIGN KEY ("system_id") REFERENCES "systems" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "object_provider_bucket" to table: "objects"
CREATE INDEX "object_provider_bucket" ON "objects" ("provider", "bucket");
-- Create index "object_status_update_time" to table: "objects"
CREATE INDEX "object_status_update_time" ON "objects" ("status", "update_time");
-- Create index "object_system_id" to table: "objects"
CREATE INDEX "object_system_id" ON "objects" ("system_id");
-- Create index "object_system_id_provider_bucket_storage_key" to table: "objects"
CREATE UNIQUE INDEX "object_system_id_provider_bucket_storage_key" ON "objects" ("system_id", "provider", "bucket", "storage_key");
-- Create "system_groups" table
CREATE TABLE "system_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "gid" bigint NOT NULL DEFAULT 0,
  "system_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "system_groups_systems_system" FOREIGN KEY ("system_id") REFERENCES "systems" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "systemgroup_system_id" to table: "system_groups"
CREATE INDEX "systemgroup_system_id" ON "system_groups" ("system_id");
-- Create index "systemgroup_system_id_gid" to table: "system_groups"
CREATE UNIQUE INDEX "systemgroup_system_id_gid" ON "system_groups" ("system_id", "gid");
-- Create index "systemgroup_system_id_name" to table: "system_groups"
CREATE UNIQUE INDEX "systemgroup_system_id_name" ON "system_groups" ("system_id", "name");
-- Create "users" table
CREATE TABLE "users" (
  "id" character varying NOT NULL,
  "create_time" timestamptz NOT NULL,
  "update_time" timestamptz NOT NULL,
  "username" character varying NOT NULL,
  "provider" character varying NOT NULL,
  "provider_id" character varying NOT NULL,
  "join_date" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_provider_provider_id" to table: "users"
CREATE UNIQUE INDEX "user_provider_provider_id" ON "users" ("provider", "provider_id");
-- Create index "user_username" to table: "users"
CREATE INDEX "user_username" ON "users" ("username");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Create "user_systems" table
CREATE TABLE "user_systems" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "uid" bigint NOT NULL DEFAULT 0,
  "gid" bigint NOT NULL DEFAULT 0,
  "username" character varying NOT NULL,
  "user_id" character varying NOT NULL,
  "system_id" character varying NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_systems_systems_system" FOREIGN KEY ("system_id") REFERENCES "systems" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_systems_users_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "usersystem_system_id" to table: "user_systems"
CREATE INDEX "usersystem_system_id" ON "user_systems" ("system_id");
-- Create index "usersystem_system_id_uid" to table: "user_systems"
CREATE UNIQUE INDEX "usersystem_system_id_uid" ON "user_systems" ("system_id", "uid");
-- Create index "usersystem_system_id_username" to table: "user_systems"
CREATE UNIQUE INDEX "usersystem_system_id_username" ON "user_systems" ("system_id", "username");
-- Create index "usersystem_user_id_system_id" to table: "user_systems"
CREATE UNIQUE INDEX "usersystem_user_id_system_id" ON "user_systems" ("user_id", "system_id");
-- Create "user_groups" table
CREATE TABLE "user_groups" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_system_id" bigint NOT NULL,
  "system_group_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "user_groups_system_groups_system_group" FOREIGN KEY ("system_group_id") REFERENCES "system_groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "user_groups_user_systems_user_system" FOREIGN KEY ("user_system_id") REFERENCES "user_systems" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "usergroup_user_system_id_system_group_id" to table: "user_groups"
CREATE UNIQUE INDEX "usergroup_user_system_id_system_group_id" ON "user_groups" ("user_system_id", "system_group_id");
