// Code generated by ent, DO NOT EDIT.

package filepath

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the filepath type in the database.
	Label = "file_path"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// Table holds the table name of the filepath in the database.
	Table = "file_paths"
)

// Columns holds all SQL columns for filepath fields.
var Columns = []string{
	FieldID,
	FieldFileID,
	FieldPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the FilePath queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}
