// Code generated by ent, DO NOT EDIT.

package filepath

import (
	"entgo.io/ent/dialect/sql"
	"github.com/starfrag-lab/retrowin-go/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FilePath {
	return predicate.FilePath(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FilePath {
	return predicate.FilePath(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FilePath {
	return predicate.FilePath(sql.FieldLTE(FieldID, id))
}

// FileID applies equality check predicate on the "file_id" field. It's identical to FileIDEQ.
func FileID(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldEQ(FieldFileID, v))
}

// FileIDEQ applies the EQ predicate on the "file_id" field.
func FileIDEQ(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldEQ(FieldFileID, v))
}

// FileIDNEQ applies the NEQ predicate on the "file_id" field.
func FileIDNEQ(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldNEQ(FieldFileID, v))
}

// FileIDIn applies the In predicate on the "file_id" field.
func FileIDIn(vs ...int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldIn(FieldFileID, vs...))
}

// FileIDNotIn applies the NotIn predicate on the "file_id" field.
func FileIDNotIn(vs ...int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldNotIn(FieldFileID, vs...))
}

// FileIDGT applies the GT predicate on the "file_id" field.
func FileIDGT(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldGT(FieldFileID, v))
}

// FileIDGTE applies the GTE predicate on the "file_id" field.
func FileIDGTE(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldGTE(FieldFileID, v))
}

// FileIDLT applies the LT predicate on the "file_id" field.
func FileIDLT(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldLT(FieldFileID, v))
}

// FileIDLTE applies the LTE predicate on the "file_id" field.
func FileIDLTE(v int64) predicate.FilePath {
	return predicate.FilePath(sql.FieldLTE(FieldFileID, v))
}

// PathIsNil applies the IsNil predicate on the "path" field.
func PathIsNil() predicate.FilePath {
	return predicate.FilePath(sql.FieldIsNull(FieldPath))
}

// PathNotNil applies the NotNil predicate on the "path" field.
func PathNotNil() predicate.FilePath {
	return predicate.FilePath(sql.FieldNotNull(FieldPath))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FilePath) predicate.FilePath {
	return predicate.FilePath(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FilePath) predicate.FilePath {
	return predicate.FilePath(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FilePath) predicate.FilePath {
	return predicate.FilePath(sql.NotPredicates(p))
}
