// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package objectMocks

import (
	"context"
	"time"

	"github.com/starfrag-lab/retrowin-go/internal/core/object"
	mock "github.com/stretchr/testify/mock"
)

// NewObjectServiceMock creates a new instance of ObjectServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewObjectServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ObjectServiceMock {
	mock := &ObjectServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ObjectServiceMock is an autogenerated mock type for the ObjectService type
type ObjectServiceMock struct {
	mock.Mock
}

type ObjectServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ObjectServiceMock) EXPECT() *ObjectServiceMock_Expecter {
	return &ObjectServiceMock_Expecter{mock: &_m.Mock}
}

// CompleteUpload provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) CompleteUpload(ctx context.Context, objectID string) (*object.Object, error) {
	ret := _mock.Called(ctx, objectID)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 *object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*object.Object, error)); ok {
		return returnFunc(ctx, objectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *object.Object); ok {
		r0 = returnFunc(ctx, objectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type ObjectServiceMock_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectID string
func (_e *ObjectServiceMock_Expecter) CompleteUpload(ctx interface{}, objectID interface{}) *ObjectServiceMock_CompleteUpload_Call {
	return &ObjectServiceMock_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", ctx, objectID)}
}

func (_c *ObjectServiceMock_CompleteUpload_Call) Run(run func(ctx context.Context, objectID string)) *ObjectServiceMock_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_CompleteUpload_Call) Return(object1 *object.Object, err error) *ObjectServiceMock_CompleteUpload_Call {
	_c.Call.Return(object1, err)
	return _c
}

func (_c *ObjectServiceMock_CompleteUpload_Call) RunAndReturn(run func(ctx context.Context, objectID string) (*object.Object, error)) *ObjectServiceMock_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) Create(ctx context.Context, cmd *object.CreateCommand) (*object.Object, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *object.CreateCommand) (*object.Object, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *object.CreateCommand) *object.Object); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *object.CreateCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ObjectServiceMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *object.CreateCommand
func (_e *ObjectServiceMock_Expecter) Create(ctx interface{}, cmd interface{}) *ObjectServiceMock_Create_Call {
	return &ObjectServiceMock_Create_Call{Call: _e.mock.On("Create", ctx, cmd)}
}

func (_c *ObjectServiceMock_Create_Call) Run(run func(ctx context.Context, cmd *object.CreateCommand)) *ObjectServiceMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *object.CreateCommand
		if args[1] != nil {
			arg1 = args[1].(*object.CreateCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_Create_Call) Return(object1 *object.Object, err error) *ObjectServiceMock_Create_Call {
	_c.Call.Return(object1, err)
	return _c
}

func (_c *ObjectServiceMock_Create_Call) RunAndReturn(run func(ctx context.Context, cmd *object.CreateCommand) (*object.Object, error)) *ObjectServiceMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ObjectServiceMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ObjectServiceMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ObjectServiceMock_Expecter) Delete(ctx interface{}, id interface{}) *ObjectServiceMock_Delete_Call {
	return &ObjectServiceMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ObjectServiceMock_Delete_Call) Run(run func(ctx context.Context, id string)) *ObjectServiceMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_Delete_Call) Return(err error) *ObjectServiceMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ObjectServiceMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *ObjectServiceMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) Find(ctx context.Context, filter object.Filter) ([]*object.Object, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, object.Filter) ([]*object.Object, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, object.Filter) []*object.Object); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, object.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type ObjectServiceMock_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - filter object.Filter
func (_e *ObjectServiceMock_Expecter) Find(ctx interface{}, filter interface{}) *ObjectServiceMock_Find_Call {
	return &ObjectServiceMock_Find_Call{Call: _e.mock.On("Find", ctx, filter)}
}

func (_c *ObjectServiceMock_Find_Call) Run(run func(ctx context.Context, filter object.Filter)) *ObjectServiceMock_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 object.Filter
		if args[1] != nil {
			arg1 = args[1].(object.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_Find_Call) Return(objects []*object.Object, err error) *ObjectServiceMock_Find_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *ObjectServiceMock_Find_Call) RunAndReturn(run func(ctx context.Context, filter object.Filter) ([]*object.Object, error)) *ObjectServiceMock_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindOne provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) FindOne(ctx context.Context, filter object.Filter) (*object.Object, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for FindOne")
	}

	var r0 *object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, object.Filter) (*object.Object, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, object.Filter) *object.Object); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, object.Filter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_FindOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOne'
type ObjectServiceMock_FindOne_Call struct {
	*mock.Call
}

// FindOne is a helper method to define mock.On call
//   - ctx context.Context
//   - filter object.Filter
func (_e *ObjectServiceMock_Expecter) FindOne(ctx interface{}, filter interface{}) *ObjectServiceMock_FindOne_Call {
	return &ObjectServiceMock_FindOne_Call{Call: _e.mock.On("FindOne", ctx, filter)}
}

func (_c *ObjectServiceMock_FindOne_Call) Run(run func(ctx context.Context, filter object.Filter)) *ObjectServiceMock_FindOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 object.Filter
		if args[1] != nil {
			arg1 = args[1].(object.Filter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_FindOne_Call) Return(object1 *object.Object, err error) *ObjectServiceMock_FindOne_Call {
	_c.Call.Return(object1, err)
	return _c
}

func (_c *ObjectServiceMock_FindOne_Call) RunAndReturn(run func(ctx context.Context, filter object.Filter) (*object.Object, error)) *ObjectServiceMock_FindOne_Call {
	_c.Call.Return(run)
	return _c
}

// FindPendingOlderThan provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) FindPendingOlderThan(ctx context.Context, olderThan time.Duration) ([]*object.Object, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for FindPendingOlderThan")
	}

	var r0 []*object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) ([]*object.Object, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) []*object.Object); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_FindPendingOlderThan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPendingOlderThan'
type ObjectServiceMock_FindPendingOlderThan_Call struct {
	*mock.Call
}

// FindPendingOlderThan is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *ObjectServiceMock_Expecter) FindPendingOlderThan(ctx interface{}, olderThan interface{}) *ObjectServiceMock_FindPendingOlderThan_Call {
	return &ObjectServiceMock_FindPendingOlderThan_Call{Call: _e.mock.On("FindPendingOlderThan", ctx, olderThan)}
}

func (_c *ObjectServiceMock_FindPendingOlderThan_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *ObjectServiceMock_FindPendingOlderThan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_FindPendingOlderThan_Call) Return(objects []*object.Object, err error) *ObjectServiceMock_FindPendingOlderThan_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *ObjectServiceMock_FindPendingOlderThan_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) ([]*object.Object, error)) *ObjectServiceMock_FindPendingOlderThan_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) GetByID(ctx context.Context, id string) (*object.Object, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*object.Object, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *object.Object); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ObjectServiceMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ObjectServiceMock_Expecter) GetByID(ctx interface{}, id interface{}) *ObjectServiceMock_GetByID_Call {
	return &ObjectServiceMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ObjectServiceMock_GetByID_Call) Run(run func(ctx context.Context, id string)) *ObjectServiceMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_GetByID_Call) Return(object1 *object.Object, err error) *ObjectServiceMock_GetByID_Call {
	_c.Call.Return(object1, err)
	return _c
}

func (_c *ObjectServiceMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*object.Object, error)) *ObjectServiceMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStorageKey provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) GetByStorageKey(ctx context.Context, systemID string, provider object.Provider, bucket string, storageKey string) (*object.Object, error) {
	ret := _mock.Called(ctx, systemID, provider, bucket, storageKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByStorageKey")
	}

	var r0 *object.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, object.Provider, string, string) (*object.Object, error)); ok {
		return returnFunc(ctx, systemID, provider, bucket, storageKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, object.Provider, string, string) *object.Object); ok {
		r0 = returnFunc(ctx, systemID, provider, bucket, storageKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, object.Provider, string, string) error); ok {
		r1 = returnFunc(ctx, systemID, provider, bucket, storageKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_GetByStorageKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStorageKey'
type ObjectServiceMock_GetByStorageKey_Call struct {
	*mock.Call
}

// GetByStorageKey is a helper method to define mock.On call
//   - ctx context.Context
//   - systemID string
//   - provider object.Provider
//   - bucket string
//   - storageKey string
func (_e *ObjectServiceMock_Expecter) GetByStorageKey(ctx interface{}, systemID interface{}, provider interface{}, bucket interface{}, storageKey interface{}) *ObjectServiceMock_GetByStorageKey_Call {
	return &ObjectServiceMock_GetByStorageKey_Call{Call: _e.mock.On("GetByStorageKey", ctx, systemID, provider, bucket, storageKey)}
}

func (_c *ObjectServiceMock_GetByStorageKey_Call) Run(run func(ctx context.Context, systemID string, provider object.Provider, bucket string, storageKey string)) *ObjectServiceMock_GetByStorageKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 object.Provider
		if args[2] != nil {
			arg2 = args[2].(object.Provider)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_GetByStorageKey_Call) Return(object1 *object.Object, err error) *ObjectServiceMock_GetByStorageKey_Call {
	_c.Call.Return(object1, err)
	return _c
}

func (_c *ObjectServiceMock_GetByStorageKey_Call) RunAndReturn(run func(ctx context.Context, systemID string, provider object.Provider, bucket string, storageKey string) (*object.Object, error)) *ObjectServiceMock_GetByStorageKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetDownloadURL provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) GetDownloadURL(ctx context.Context, id string) (string, time.Time, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDownloadURL")
	}

	var r0 string
	var r1 time.Time
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, time.Time, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) time.Time); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(time.Time)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// ObjectServiceMock_GetDownloadURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDownloadURL'
type ObjectServiceMock_GetDownloadURL_Call struct {
	*mock.Call
}

// GetDownloadURL is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ObjectServiceMock_Expecter) GetDownloadURL(ctx interface{}, id interface{}) *ObjectServiceMock_GetDownloadURL_Call {
	return &ObjectServiceMock_GetDownloadURL_Call{Call: _e.mock.On("GetDownloadURL", ctx, id)}
}

func (_c *ObjectServiceMock_GetDownloadURL_Call) Run(run func(ctx context.Context, id string)) *ObjectServiceMock_GetDownloadURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_GetDownloadURL_Call) Return(s string, time1 time.Time, err error) *ObjectServiceMock_GetDownloadURL_Call {
	_c.Call.Return(s, time1, err)
	return _c
}

func (_c *ObjectServiceMock_GetDownloadURL_Call) RunAndReturn(run func(ctx context.Context, id string) (string, time.Time, error)) *ObjectServiceMock_GetDownloadURL_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateUpload provides a mock function for the type ObjectServiceMock
func (_mock *ObjectServiceMock) InitiateUpload(ctx context.Context, cmd *object.InitiateUploadCommand) (*object.UploadSession, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for InitiateUpload")
	}

	var r0 *object.UploadSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *object.InitiateUploadCommand) (*object.UploadSession, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *object.InitiateUploadCommand) *object.UploadSession); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.UploadSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *object.InitiateUploadCommand) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ObjectServiceMock_InitiateUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateUpload'
type ObjectServiceMock_InitiateUpload_Call struct {
	*mock.Call
}

// InitiateUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *object.InitiateUploadCommand
func (_e *ObjectServiceMock_Expecter) InitiateUpload(ctx interface{}, cmd interface{}) *ObjectServiceMock_InitiateUpload_Call {
	return &ObjectServiceMock_InitiateUpload_Call{Call: _e.mock.On("InitiateUpload", ctx, cmd)}
}

func (_c *ObjectServiceMock_InitiateUpload_Call) Run(run func(ctx context.Context, cmd *object.InitiateUploadCommand)) *ObjectServiceMock_InitiateUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *object.InitiateUploadCommand
		if args[1] != nil {
			arg1 = args[1].(*object.InitiateUploadCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ObjectServiceMock_InitiateUpload_Call) Return(uploadSession *object.UploadSession, err error) *ObjectServiceMock_InitiateUpload_Call {
	_c.Call.Return(uploadSession, err)
	return _c
}

func (_c *ObjectServiceMock_InitiateUpload_Call) RunAndReturn(run func(ctx context.Context, cmd *object.InitiateUploadCommand) (*object.UploadSession, error)) *ObjectServiceMock_InitiateUpload_Call {
	_c.Call.Return(run)
	return _c
}
